import { DictationEntry, DictionaryEntry, SnippetEntry, StyleProfile, ScratchpadEntry, FlowSettings } from '../types';

export const INITIAL_STYLES: StyleProfile[] = [
  {
    id: 'style-balanced',
    name: 'Natural / Balanced',
    description: 'Removes filler words (um, uh) and formats punctuation cleanly while preserving your natural tone.',
    formalityLevel: 'balanced',
    contractionPolicy: 'preserve',
    useBulletPoints: false,
    isEnabled: true,
    appMappings: ['Default', 'Notion', 'Obsidian', 'Chrome'],
  },
  {
    id: 'style-formal',
    name: 'Formal / Professional',
    description: 'Expands contractions, elevates sentence structure, and ensures professional cadence for business emails.',
    formalityLevel: 'formal',
    contractionPolicy: 'expand',
    useBulletPoints: false,
    isEnabled: true,
    appMappings: ['Outlook', 'Microsoft Word', 'Teams'],
  },
  {
    id: 'style-casual',
    name: 'Casual / Conversational',
    description: 'Allows contractions, friendly phrasing, and relaxed punctuation for team chats and messaging.',
    formalityLevel: 'casual',
    contractionPolicy: 'contract',
    useBulletPoints: false,
    isEnabled: true,
    appMappings: ['Slack', 'Discord', 'WhatsApp'],
  },
  {
    id: 'style-concise',
    name: 'Concise / Bulleted',
    description: 'Summarizes key thoughts into tight, actionable items ideal for issue trackers and task lists.',
    formalityLevel: 'balanced',
    contractionPolicy: 'contract',
    useBulletPoints: true,
    isEnabled: true,
    appMappings: ['Jira', 'Linear', 'GitHub'],
  },
  {
    id: 'style-developer',
    name: 'Developer / Coding Mode',
    description: 'Enables spoken casing commands (camel case, snake case, pascal case) and preserves code identifiers & file paths.',
    formalityLevel: 'balanced',
    contractionPolicy: 'preserve',
    useBulletPoints: false,
    isDeveloperMode: true,
    isEnabled: true,
    appMappings: ['VS Code', 'Visual Studio', 'Windows Terminal', 'Cursor'],
  },
];

export const INITIAL_DICTIONARY: DictionaryEntry[] = [
  {
    id: 'dict-1',
    term: 'Kubernetes',
    phonetic: '/kjuːbərˈnɛtiːz/',
    matchesHint: "Matches: 'cooberneties', 'cube nettes'",
    replacement: 'k8s',
    category: 'Tech / Cloud',
    tag: 'Literal',
    isCorrection: true,
    isFavorite: true,
    createdAt: '2026-09-10T10:00:00Z',
  },
  {
    id: 'dict-2',
    term: 'Wispr',
    phonetic: '/wɪspər/',
    matchesHint: 'Context: dictation app references',
    replacement: 'Wispr Flow',
    category: 'Product',
    tag: 'Brand Capital',
    isCorrection: true,
    isFavorite: true,
    createdAt: '2026-09-10T10:05:00Z',
  },
  {
    id: 'dict-3',
    term: 'Dr. Aris Thorne',
    phonetic: '/ɛərɪs θɔːrn/',
    matchesHint: "Matches: 'Doctor Aris Thorn', 'Aeris'",
    replacement: 'Dr. Aris Thorne, MD',
    category: 'Medical / Name',
    tag: 'Title Expansion',
    isCorrection: true,
    isFavorite: true,
    createdAt: '2026-09-11T12:00:00Z',
  },
  {
    id: 'dict-4',
    term: 'GraphQL API',
    phonetic: '/græf kjuː ɛl/',
    matchesHint: "Matches: 'graph q l', 'graph cue ell'",
    replacement: 'GraphQL',
    category: 'Tech',
    tag: 'Exact Case',
    isCorrection: true,
    isFavorite: false,
    createdAt: '2026-09-11T14:30:00Z',
  },
  {
    id: 'dict-5',
    term: 'Antigravity',
    phonetic: '/æn.tiˈɡræv.ə.ti/',
    matchesHint: 'Product library reference',
    replacement: 'Antigravity UI',
    category: 'Design System',
    tag: 'Product',
    isCorrection: true,
    isFavorite: false,
    createdAt: '2026-09-12T09:15:00Z',
  },
];

export const INITIAL_SNIPPETS: SnippetEntry[] = [
  {
    id: 'snip-1',
    trigger: 'meeting link',
    expansion: 'https://meet.google.com/abc-defg-hij',
    createdAt: '2026-09-10T08:00:00Z',
  },
  {
    id: 'snip-2',
    trigger: 'my intro',
    expansion: 'Hi, I am working on system-wide voice productivity for Windows with local-first inference.',
    createdAt: '2026-09-10T08:05:00Z',
  },
  {
    id: 'snip-3',
    trigger: 'bug report template',
    expansion: 'Environment: Windows 11 x64. Steps: 1. Hold Right Alt. 2. Speak. Result: ..., Expected: ...',
    createdAt: '2026-09-11T11:20:00Z',
  },
  {
    id: 'snip-4',
    trigger: 'sign off',
    expansion: 'Best regards, Barathwaj',
    createdAt: '2026-09-11T15:00:00Z',
  },
];

export const INITIAL_HISTORY: DictationEntry[] = [
  {
    id: 'hist-1',
    sessionId: 'sess-1001',
    createdAt: 'Today, 2:18 PM',
    timeShort: '2:18 PM',
    durationMs: 8400,
    durationText: '8.4s',
    characterCount: 228,
    wordCount: 42,
    language: 'English (US)',
    application: 'Microsoft Teams',
    applicationCategory: 'Communication',
    target: 'Direct Message',
    mode: 'Polished',
    state: 'Completed',
    isFavorite: true,
    latency: '120ms (Int8)',
    engine: 'FLOW Local Int8 v3.2',
    text: 'Hey Jordan, could you make sure the pull request for the zero-latency audio engine gets merged into staging before our 3:30 sync? We already ran the Int8 inference benchmark tests locally.',
  },
  {
    id: 'hist-2',
    sessionId: 'sess-1002',
    createdAt: 'Today, 1:42 PM',
    timeShort: '1:42 PM',
    durationMs: 14100,
    durationText: '14.1s',
    characterCount: 374,
    wordCount: 68,
    language: 'English (US)',
    application: 'Visual Studio Code',
    applicationCategory: 'Developer',
    target: 'audio_buffer.cpp',
    mode: 'Code Mode',
    state: 'Completed',
    isFavorite: false,
    latency: '108ms (Int8)',
    engine: 'FLOW Local Int8 v3.2',
    text: 'Refactor the audio stream buffer controller to handle high packet bursts without dropping PCM samples. Also inject error handling for missing device handles gracefully.',
  },
  {
    id: 'hist-3',
    sessionId: 'sess-1003',
    createdAt: 'Today, 11:05 AM',
    timeShort: '11:05 AM',
    durationMs: 6200,
    durationText: '6.2s',
    characterCount: 168,
    wordCount: 31,
    language: 'English (US)',
    application: 'Slack',
    applicationCategory: 'Communication',
    target: '#product-architecture',
    mode: 'Polished',
    state: 'Completed',
    isFavorite: true,
    latency: '95ms (Int8)',
    engine: 'FLOW Local Int8 v3.2',
    text: 'All client telemetry points towards zero drop-offs when Whisper models run in background threads on Windows 11 Fluent shells.',
  },
  {
    id: 'hist-4',
    sessionId: 'sess-1004',
    createdAt: 'Yesterday, 10:15 AM',
    timeShort: 'Yesterday, 10:15 AM',
    durationMs: 22800,
    durationText: '22.8s',
    characterCount: 618,
    wordCount: 114,
    language: 'English (US)',
    application: 'Microsoft Word',
    applicationCategory: 'Productivity',
    target: 'Specification_Doc_v2.docx',
    mode: 'Polished',
    state: 'Completed',
    isFavorite: false,
    latency: '140ms (FP16)',
    engine: 'FLOW Local FP16 v3.2',
    text: 'The primary design thesis of local voice productivity relies upon immediate tactile acknowledgment. By utilizing Windows Mica layered backdrops and direct WASAPI audio capture streams, latency vanishes completely.',
  },
  {
    id: 'hist-5',
    sessionId: 'sess-1005',
    createdAt: 'Today, 9:04 AM',
    timeShort: '9:04 AM',
    durationMs: 5100,
    durationText: '5.1s',
    characterCount: 135,
    wordCount: 24,
    language: 'English (US)',
    application: 'Google Chrome',
    applicationCategory: 'Browser',
    target: 'github.com/microsoft',
    mode: 'Raw Dictate',
    state: 'Completed',
    isFavorite: false,
    latency: '89ms (Int8)',
    engine: 'FLOW Local Int8 v3.2',
    text: 'Github repo microsoft directml whisper onnx runtime acceleration instructions for Windows 11 build 22631.',
  },
  {
    id: 'hist-6',
    sessionId: 'sess-1006',
    createdAt: 'Yesterday, 2:10 PM',
    timeShort: 'Yesterday, 2:10 PM',
    durationMs: 18200,
    durationText: '18.2s',
    characterCount: 590,
    wordCount: 110,
    language: 'English (US)',
    application: 'Outlook',
    applicationCategory: 'Communication',
    target: 'Inbox / Approvals',
    mode: 'Polished',
    state: 'Completed',
    isFavorite: true,
    latency: '115ms (Int8)',
    engine: 'FLOW Local Int8 v3.2',
    text: "Hi Marcus, thanks for the contract update. I reviewed section 3 and marked my approvals. Let's schedule a 15-minute sync on Thursday.",
  },
];

export const INITIAL_SCRATCHPAD: ScratchpadEntry[] = [
  {
    id: 'note-1',
    title: 'FLOW Windows Engineering Architecture',
    content: `# FLOW — AI Voice Productivity for Windows

## Core Architecture Principles
1. **100% Offline Sovereignty**: Audio captured strictly on-device using local Whisper weights.
2. **Inviolable Zero-Enter Invariant**: Never simulates Enter or form submissions.
3. **Non-Activating Floating Flow Bar**: Win32 window with WS_EX_NOACTIVATE | WS_EX_TOPMOST.
4. **Target Application Support**: Seamless dictation into VS Code, Chrome, Slack, Notion, Word.`,
    createdAt: '2026-09-12T10:00:00Z',
    updatedAt: '2026-09-13T07:00:00Z',
    isPinned: true,
    wordCount: 54,
    characterCount: 420,
  },
  {
    id: 'note-2',
    title: 'Keyboard Shortcuts Reference',
    content: `- Hold [Right Alt]: Push-to-Talk dictation
- Double-Tap [Right Alt]: Hands-free continuous dictation toggle
- [Shift + Right Alt]: Backtrack Undo previous insertion
- [Escape]: Cancel active recording without inserting text`,
    createdAt: '2026-09-12T11:30:00Z',
    updatedAt: '2026-09-12T11:45:00Z',
    isPinned: false,
    wordCount: 30,
    characterCount: 220,
  },
];

export const INITIAL_SETTINGS: FlowSettings = {
  activeMic: 'Default Windows Audio Endpoint (WASAPI)',
  sensitivity: 75,
  hotkey: 'Hold [Right Alt]',
  handsFreeHotkey: 'Double-Tap [Right Alt]',
  backtrackHotkey: 'Shift + Right Alt',
  language: 'English (US)',
  zeroEnterInvariant: true,
  retentionPolicy: 'unlimited',
  activeStyleId: 'style-balanced',
  soundFeedback: true,
};
