using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using Flow.Core.Context;
using Flow.Core.Language;
using Flow.Core.TranscriptProcessing;
using Xunit;

namespace Flow.Core.Tests.Developer;

/// <summary>
/// Dedicated Adversarial Prose Corpus Test Suite (Section 28).
/// Contains 550 curated natural-language sentences across 12 distinct categories containing potential developer keywords
/// (function, method, class, struct, record, enum, interface, protocol, arrow, dot, colon, underscore, equals, camel case, snake case, API, database, repository, path, terminal, at home, at work, at school, at noon, at dawn, etc.)
/// and rigorously verifies that exactly ZERO unintended developer transformations occur in general prose context.
/// </summary>
public class AdversarialProseCorpusTests
{
    private readonly TranscriptProcessingPipeline _pipeline = new();

    private static readonly FormattingOptions ProseOptions = new(
        Category: ApplicationCategory.GeneralProse,
        TargetApplication: "notepad",
        DeveloperContext: new DeveloperContext("notepad", ApplicationCategory.GeneralProse, LanguageCatalog.English, IdentifierCasingStyle.None)
    );

    public static IEnumerable<object[]> CuratedAdversarialProseCases()
    {
        var sentences = new[]
        {
            // Category: FunctionMethod (50 cases)
            "The function of the human kidney is to filter waste products from the blood.",
            "The primary function of the lungs is gas exchange between air and blood.",
            "The liver performs a vital function in detoxifying chemical compounds.",
            "The digestive function of the stomach breaks down complex proteins.",
            "The endocrine function of the pancreas regulates glucose levels.",
            "The function of this charitable foundation is supporting underprivileged youth.",
            "The social function began with an inspiring address by the keynote speaker.",
            "The executive function of the human brain governs planning and impulse control.",
            "The primary function of chlorophyll in plants is photosynthesis.",
            "The function of the cooling tower is removing heat from industrial processes.",
            "The civic function celebrated the historic anniversary of the municipality.",
            "The main function of the committee is reviewing annual grant applications.",
            "The optical function of the cornea is focusing incoming light onto the retina.",
            "The historical function of the fortress was defending the harbor from invaders.",
            "The judicial function of the court is interpreting statutory legislation.",
            "The method used by the archaeologist uncovered several ancient ceramic vessels.",
            "Our method for cultivating organic vegetables uses zero synthetic fertilizers.",
            "The scientific method requires verifiable hypotheses and repeatable experiments.",
            "She demonstrated an effective method for organizing domestic finances.",
            "The Montessori method encourages self-directed learning and tactile discovery.",
            "A traditional method of olive oil extraction uses large granite stones.",
            "The Socratic method engages students through disciplined probing questions.",
            "Their method of conducting qualitative interviews yielded deep sociological insights.",
            "An innovative method for seawater desalination was piloted along the coast.",
            "The classical method of learning piano requires daily practice with scales.",
            "The forensic method identified the origin of the fiber under the microscope.",
            "The method of preserving dried fruits dates back thousands of years.",
            "A rigorous method for statistical sampling ensured a representative cohort.",
            "The surgical method minimized recovery time for patients undergoing joint replacement.",
            "Her pedagogical method balanced structured instruction with creative exploration.",
            "Every function in municipal administration must remain open to public scrutiny.",
            "The diplomatic function hosted ambassadors from fourteen neighboring nations.",
            "The biological function of migration in birds is avoiding harsh winter climates.",
            "The acoustic function of the opera hall depends on curved wooden panels.",
            "The mechanical function of the suspension absorbs shocks from uneven roads.",
            "A reliable method for testing water purity was deployed across rural schools.",
            "The ethnographic method immersed the anthropologist in the village for two years.",
            "His method for resolving workplace conflicts focused on active empathetic listening.",
            "The algebraic function describes the parabolic trajectory of a projectile.",
            "A standard method for measuring atmospheric pressure uses a mercury barometer.",
            "The cultural function brought together traditional dancers from several islands.",
            "The sensory function of the inner ear coordinates both hearing and equilibrium.",
            "The method of making handcrafted paper has been preserved by local artisans.",
            "The educational function of public museums cannot be overstated.",
            "An empirical method for evaluating soil fertility relies on core nitrogen tests.",
            "The function of the insulation is preventing heat loss during winter months.",
            "Their method of negotiating trade agreements prioritized environmental safeguards.",
            "The aesthetic function of the garden provides visitors with tranquility.",
            "A non-invasive method for cardiac screening was introduced at the clinic.",
            "The protective function of the ozone layer shields life from ultraviolet rays.",
            // Category: ClassStructRecordEnum (60 cases)
            "The class starts at ten in the morning on Tuesdays and Thursdays.",
            "My class project in marine biology is due tomorrow afternoon.",
            "The class was held yesterday in the large lecture auditorium.",
            "The class schedule changed after the university announced the holiday.",
            "A class of thirty enthusiastic students attended the creative writing workshop.",
            "We booked a first class train compartment for our journey across Europe.",
            "She comes from a hard-working class family that values community service.",
            "He delivered a master class in ceramic pottery to visiting international artists.",
            "Each class has twenty-five desks arranged in collaborative circular clusters.",
            "Our class reunion was scheduled for the first warm weekend in September.",
            "The upper class residential district features century-old limestone mansions.",
            "The middle class expansion contributed significantly to postwar economic growth.",
            "A yoga class was organized in the park every Saturday sunrise.",
            "The biology class dissected owl pellets to study predator-prey relationships.",
            "The cooking class taught beginners how to prepare authentic pasta dough.",
            "She graduated at the very top of her high school graduating class.",
            "The evening class in conversational French was completely fully booked.",
            "A fitness class for senior citizens meets three mornings each week.",
            "The ceramics class displayed their glazed vases in the library gallery.",
            "An introductory class in astronomy visits the rooftop observatory weekly.",
            "The record was deleted from the courthouse register following the expungement.",
            "The athlete broke the world record in the four-hundred-meter hurdles yesterday.",
            "The medical record was transferred securely between the two specialist clinics.",
            "The historic record indicates that the bridge was constructed in nineteen twelve.",
            "The vinyl record spun smoothly on the restored turntable in the lounge.",
            "The track and field record had remained unbroken for nearly thirty years.",
            "She keeps a meticulous personal record of all daily household expenditures.",
            "The fossil record reveals sudden bursts of evolutionary diversification.",
            "The court reporter ensured every spoken word entered the official record.",
            "The geological record shows widespread evidence of alternating glacial periods.",
            "A weather station recorded the coldest temperature on record for the valley.",
            "The school attendance record improved dramatically after the bus route expanded.",
            "His criminal record was clean and he received full security clearance.",
            "The dental record confirmed the patient had received orthodontic treatment.",
            "The financial audit examined every transaction record from the previous quarter.",
            "The company achieved a record annual dividend payout for shareholders.",
            "The census record provided valuable genealogical clues about her ancestors.",
            "The seismic record detected micro-tremors several hours before the main shock.",
            "An ancient astronomical record noted the sudden appearance of a bright supernova.",
            "The patient medical history was compiled into a single consolidated record.",
            "The structural integrity of the suspension bridge was evaluated by engineers.",
            "The social structure of dolphin pods displays remarkable cooperation.",
            "The cellular structure of plant leaves includes thick protective cell walls.",
            "The architectural structure combined Roman arches with modern steel trusses.",
            "The organizational structure of the nonprofit relies on regional chapters.",
            "The crystalline structure of quartz exhibits six-sided pyramidal prisms.",
            "The sentence structure in her poetry shifts between formal and conversational.",
            "The economic structure of the island depends primarily on eco-tourism.",
            "The geological structure of the mountain range resulted from tectonic uplift.",
            "The atomic structure of gold explains its resistance to oxidation.",
            "The family structure in traditional agricultural societies was extended.",
            "The crystalline structure of ice creates intricate hexagonal snowflakes.",
            "The governance structure of the cooperative grants equal votes to all members.",
            "The bone structure of avian wings evolved from ancestral reptilian limbs.",
            "The physical structure of the coral reef provides habitat for thousands of species.",
            "The enumeration of the census took nearly eighteen months to complete.",
            "The botanical classification enumerates three distinct varieties of wild orchids.",
            "His speech included a detailed enumeration of past legislative achievements.",
            "The legal statute provides an enumeration of fundamental civil liberties.",
            "The museum catalog offers an enumeration of all artifacts found at the dig site.",
            // Category: InterfaceProtocol (40 cases)
            "The interface between land and sea creates unique tidal marsh ecosystems.",
            "The user interface of the vintage camera relied on manual brass dials.",
            "The delicate interface between nerve fibers and muscle cells facilitates motion.",
            "The mechanical interface between the engine and gearbox required new bearings.",
            "An artistic interface between traditional pottery and digital glaze design emerged.",
            "The cultural interface between neighboring nations fostered mutual culinary exchange.",
            "The thermal interface material transferred heat from the lamp to the aluminum housing.",
            "The linguistic interface between Spanish and Portuguese reveals common roots.",
            "The trade interface between the two port cities flourished for centuries.",
            "The physical interface of the ancient sundial used an angled bronze gnomon.",
            "The biological interface within the placenta regulates nutrient and oxygen transfer.",
            "The psychological interface between memory and emotion influences human decision making.",
            "The architectural interface between interior rooms and the garden featured sliding glass.",
            "The boundary interface between tectonic plates produces deep oceanic trenches.",
            "The musical interface between violin strings and the spruce soundboard creates warmth.",
            "The social interface between generations improved through community storytelling circles.",
            "The acoustic interface between air and water causes sound waves to refract sharply.",
            "The diplomatic interface between the two embassies remained active throughout negotiations.",
            "The tactile interface of braided leather provides a secure grip on the saddle.",
            "The biochemical interface between enzymes and substrates requires exact geometric fit.",
            "The maritime protocol requires ships to signal with fog horns during low visibility.",
            "The diplomatic protocol dictated the seating arrangement at the state dinner.",
            "The safety protocol for laboratory experiments mandates protective goggles at all times.",
            "The Kyoto protocol established binding international targets for emission reductions.",
            "The hospital protocol for emergency admissions was updated by the medical board.",
            "The royal protocol specifies that guests should stand when the sovereign enters.",
            "The experimental protocol was submitted to the ethics committee for prior approval.",
            "The emergency protocol for chemical spills includes immediate room evacuation.",
            "The ceremonial protocol for the coronation dates back to the fourteenth century.",
            "The quarantine protocol for imported livestock requires thirty days of isolation.",
            "The flight protocol requires pilots to perform pre-flight checks before taxiing.",
            "The security protocol at the international border was tightened following the alert.",
            "The evacuation protocol for coastal villages was tested during the tsunami drill.",
            "The clinical protocol for vaccine trials involves three distinct testing phases.",
            "The standard protocol for cleanroom manufacturing requires specialized bunny suits.",
            "The academic protocol for doctoral defenses requires an external visiting examiner.",
            "The archaeological protocol for artifact excavation records stratigraphic depth precisely.",
            "The international protocol against wildlife trafficking was ratified by eighty nations.",
            "The athletic protocol for doping control includes both urine and blood samples.",
            "The communication protocol between base camp and climbers used VHF radio handsets.",
            // Category: Arrow (40 cases)
            "The arrow points upward to indicate the elevator location in the lobby.",
            "The green arrow points right toward the express lane on the highway.",
            "The weathered wooden arrow pointed along the forest hiking trail toward the summit.",
            "An ornate bronze arrow was discovered inside the ancient royal burial mound.",
            "The painted white arrow on the asphalt directed drivers toward the parking deck.",
            "Cupid launched a golden arrow in classical mythology to inspire sudden affection.",
            "The archer released the cedar arrow and struck the center of the straw target.",
            "A neon arrow pointed toward the entrance of the retro twenty-four-hour diner.",
            "The compass arrow wavered momentarily before settling firmly on magnetic north.",
            "The stone arrowhead was chipped from black obsidian with remarkable precision.",
            "A glowing red arrow indicated the emergency exit route through the corridor.",
            "The weather vane featured an iron arrow that rotated with shifting coastal winds.",
            "The map featured a small decorative arrow indicating the prevailing trade winds.",
            "The wooden signpost had a carved arrow indicating the distance to the waterfall.",
            "The trajectory of the tipped arrow followed a parabolic arc through the morning air.",
            "An ancient quivered arrow was recovered intact from the melting alpine glacier.",
            "The directional arrow on the subway floor guided commuters toward line six.",
            "A silver arrow pendant was gifted to her as a talisman for safe travels.",
            "The traffic sign displayed an arrow curving sharply around the cliff edge.",
            "The hunting arrow was fletched with goose feathers to ensure flight stability.",
            "The arrow pointed toward the historical monument situated across the town square.",
            "A flashing yellow arrow warned motorists that oncoming traffic had right of way.",
            "The painted arrow on the trail marker had faded after years of winter blizzards.",
            "He found an ancient flint arrow head while tilling the southern barley field.",
            "The golden arrow gleamed under the museum spotlight in the medieval exhibition.",
            "The schematic diagram included a small blue arrow showing water flow direction.",
            "An illuminated arrow guided late arrivals to their seats in the dark auditorium.",
            "The archer inspected each arrow shaft for straightness before the championship match.",
            "A carved wooden arrow pointed toward the historic covered bridge down the lane.",
            "The compass arrow pointed directly toward the distant snow-capped peaks.",
            "The road sign featured an arrow indicating a detour around bridge construction.",
            "The flight of the fletched arrow was silent as it traveled toward the archery target.",
            "An arrow carved into the tree bark marked the boundary of the old timber claim.",
            "The digital display showed a rising arrow alongside the ambient temperature readout.",
            "The exit arrow was visible even through the dense morning fog on the tarmac.",
            "The heraldic shield depicted three silver arrows crossed beneath a golden crown.",
            "The museum docent pointed out a poisoned arrow used by indigenous hunters.",
            "A large red arrow painted on the warehouse floor designated the loading zone.",
            "The compass arrow spun erratically near the iron-rich basalt rock formation.",
            "The directional arrow on the hiking map was oriented toward true geographic north.",
            // Category: Dot (40 cases)
            "Please put a dot after the sentence to conclude the paragraph properly.",
            "Her favorite summer dress featured small navy blue polka dots on white cotton.",
            "The distant sailboat appeared as a tiny white dot on the vast blue ocean.",
            "A red dot on the weather radar indicated intense convective thunderstorm activity.",
            "Connect the dots on the children's activity sheet to reveal the hidden cartoon animal.",
            "The radar screen displayed a persistent luminous dot moving steadily eastward.",
            "The artist used minute dots of contrasting paint in the pointillist technique.",
            "A solitary green dot on the instrument panel confirmed the backup generator was online.",
            "The ladybug crawled across the rose leaf displaying seven distinct black dots.",
            "The astronomer identified a faint dot of light as a newly discovered trans-Neptunian object.",
            "She placed a dot of dark chocolate frosting on top of each miniature cupcake.",
            "The laser pointer projected a tiny red dot onto the presentation projection screen.",
            "The printed fabric had an irregular pattern of golden dots woven into the silk.",
            "A small dot of moisture formed on the chilled exterior of the drinking glass.",
            "The domino tile had six white dots indented into the polished black resin.",
            "The satellite photograph revealed a dark circular dot in the center of the volcanic crater.",
            "The navigation chart marked shallow sandbars with clusters of stippled black dots.",
            "A bright yellow dot on the city map designated the central public transit terminal.",
            "The dragonfly had iridescent sapphire dots along the margins of its transparent wings.",
            "He noticed a small oil dot on the driveway where the vintage roadster had parked.",
            "The microscope revealed tiny lipid dots suspended within the cellular cytoplasm.",
            "The leopard fur coat pattern consists of rosettes surrounding dark central dots.",
            "She carefully placed a dot of amber varnish over the repaired acoustic violin seam.",
            "The digital clock display had two pulsing green dots separating hours and minutes.",
            "The ancient parchment map had small red dots marking freshwater desert oases.",
            "A singular bright dot appeared in the dusk sky signaling the emergence of Venus.",
            "The dice rolled across the felt tabletop landing on the side with five dots.",
            "The silk necktie featured miniature silver dots against a midnight blue background.",
            "The sound technician adjusted the audio slider until the warning red dot disappeared.",
            "A dot of crimson ink bled through the thin handmade rice paper stationary.",
            "The radar tracking station lost sight of the faint dot when the glider banked.",
            "The ladybird beetle had distinctive orange dots on its glossy protective wing covers.",
            "The braille alphabet uses raised embossed dots arranged in rectangular six-dot cells.",
            "A single dot on the timeline represented a transformative century of cultural renaissance.",
            "The painter applied thousands of micro dots to create subtle atmospheric gradients.",
            "The optical target had concentric white circles surrounding a high-contrast black dot.",
            "The child drew a smiling sun with yellow rays and orange dots for freckles.",
            "A solitary dot of red wax sealed the confidential diplomatic dispatch.",
            "The constellation chart represented faint stars with increasingly smaller black dots.",
            "The monitor displayed a pulsating green dot tracking the maritime telemetry buoy.",
            // Category: Colon (40 cases)
            "The colon in the patient showed no pathological signs of diverticulitis or polyps.",
            "A routine colon screening is recommended for all adults over the age of forty-five.",
            "The primary physiological function of the human colon is absorbing water and electrolytes.",
            "The colon examination was completed without any discomfort using mild sedation.",
            "Nutritional scientists emphasize that dietary fiber supports healthy microflora in the colon.",
            "The gastroenterologist reviewed the endoscopic photographs of the transverse colon carefully.",
            "Chronic inflammation of the colon is a hallmark of inflammatory bowel conditions.",
            "The ascending colon travels upward along the right side of the abdominal cavity.",
            "The descending colon transitions into the sigmoid colon near the left pelvic brim.",
            "Water absorption primarily occurs throughout the mucosal lining of the large colon.",
            "The biopsy taken from the sigmoid colon confirmed the lesion was entirely benign.",
            "A high-fiber diet promotes regular peristaltic contractions through the colon lumen.",
            "The clinical trial investigated probiotic efficacy in soothing irritable colon symptoms.",
            "The anatomical model illustrated the anatomical relationship between the cecum and colon.",
            "Microscopic examination of the colon tissue revealed intact goblet cell architecture.",
            "The colon was thoroughly prepared with clear fluids before the scheduled procedure.",
            "Bacterial fermentation inside the human colon produces essential short-chain fatty acids.",
            "The surgeon carefully inspected the vascular supply to the splenic flexure of the colon.",
            "Patients recovering from colon resection are introduced to soft bland foods gradually.",
            "Ultrasound imaging ruled out acute obstruction in the lower pelvic colon.",
            "Use a colon after an introductory independent clause when announcing a list.",
            "The formal business letter opened with the recipient name followed by a formal colon.",
            "In traditional English grammar a colon introduces an explanation or elaboration.",
            "The title of the academic monograph featured a colon preceding the secondary subtitle.",
            "The digital timer display featured a blinking colon between minutes and seconds.",
            "The author placed a colon before quoting the memorable words of the philosopher.",
            "A colon should not be placed between a preposition and its direct grammatical object.",
            "The recipe card formatted ingredients neatly after an introductory header and colon.",
            "The theatrical script indicated speaker names in bold uppercase followed by a colon.",
            "Her journal entry began with the calendar date followed by an elegant ink colon.",
            "The architectural specification sheet utilized a colon to separate dimensions from notes.",
            "The Latin inscription on the cathedral archway used a carved stone colon as a separator.",
            "In legal citations a colon frequently separates volume numbers from specific page references.",
            "The dictionary entry listed word origin and phonetic pronunciation after a bold colon.",
            "The bibliographic entry separated the publishing house from the city with a colon.",
            "A colon introduced the executive summary at the beginning of the annual report.",
            "The museum artifact plaque featured the dynasty name followed by a descriptive colon.",
            "The conference schedule printed presentation start times using a standard numeric colon.",
            "The textbook chapter header had the chapter number and a colon before the chapter title.",
            "The punctuation manual explained the subtle stylistic differences between a semicolon and colon.",
            // Category: Underscore (40 cases)
            "The recent financial audit serves to underscore the need for internal accounting controls.",
            "Her passionate speech aimed to underscore the urgency of coastal flood defenses.",
            "The museum exhibition sought to underscore the cultural achievements of the civilization.",
            "These empirical findings underscore the critical importance of early childhood nutrition.",
            "The diplomat wished to underscore the long-standing peaceful alliance between the nations.",
            "The dramatic cello melody seemed to underscore the poignant tragedy of the cinematic scene.",
            "Statistical analyses underscore the strong correlation between literacy and longevity.",
            "The recent heatwave should underscore the tangible reality of changing climate patterns.",
            "The keynote presentation wanted to underscore three fundamental tenets of sustainable design.",
            "Her personal memoirs underscore the immense resilience of women during the wartime blockade.",
            "The safety inspection served to underscore persistent structural maintenance deficits.",
            "The historical documents underscore the complex motives behind the colonial expeditions.",
            "The tragic accident will underscore the imperative for mandatory seatbelt legislation.",
            "The conductor asked the string section to underscore the gentle flute solo softly.",
            "These clinical results underscore the therapeutic potential of the novel compound.",
            "The architectural report sought to underscore the historical value of the nineteenth-century facade.",
            "The editorial column wanted to underscore the constitutional protection of journalistic sources.",
            "The ongoing teacher shortages underscore the necessity of competitive educational salaries.",
            "The photographic essay seemed to underscore the stark isolation of Arctic research outposts.",
            "The laboratory safety manual cannot underscore enough the mandatory use of safety shields.",
            "The designer drew a single thin pencil underscore beneath the calligraphic headline.",
            "The printed title was framed with an ornate decorative underscore of gilded floral vines.",
            "A subtle red underscore in the proofreading markup indicated a potential spelling slip.",
            "The typographer added an elegant brass underscore rule below the author byline.",
            "An underscore was sketched beneath the key thesis statement in his lecture notes.",
            "The calligrapher finished the wedding invitation with a flourish and a golden underscore.",
            "The architectural blueprint featured an underscore beneath every room dimension figure.",
            "A double underscore was drawn below the signature block on the treaty document.",
            "The vintage letterpress poster used a heavy wooden underscore below the main date.",
            "An engraved silver tray featured the family motto with an ornate floral underscore.",
            "The teacher used an underscore to emphasize the irregular verb conjugations on the chalkboard.",
            "A dotted underscore in the legal contract signified where the notary seal belonged.",
            "The book cover art utilized a vibrant turquoise underscore beneath the author surname.",
            "An ink underscore highlighted the critical warning clause in the maritime charter.",
            "The botanical illustration included an underscore beneath the Latin binomial name.",
            "A clean horizontal underscore separated the document header from the primary text.",
            "The editor suggested an underscore beneath the section subheadings for visual clarity.",
            "The fountain pen left a bold wet underscore across the rough laid paper parchment.",
            "A decorative wave pattern served as an artistic underscore beneath the chapter ending.",
            "The memorial plaque featured an underscore beneath the names of the fallen volunteers.",
            // Category: Equals (50 cases)
            "In elementary mathematics two plus two equals four without any uncertainty.",
            "A kilometer approximately equals six-tenths of an imperial statute mile.",
            "One metric ton equals one thousand kilograms of calibrated mass.",
            "A square mile approximately equals six hundred and forty fertile acres.",
            "The pressure exerted by the column of water equals depth times density.",
            "Total revenue minus total operational expenditures equals net commercial profit.",
            "In physical chemistry energy equals Planck constant multiplied by radiation frequency.",
            "The sum of interior angles in any Euclidean triangle always equals one hundred eighty degrees.",
            "One nautical league historically equals three international nautical miles at sea.",
            "The force required to accelerate a body equals mass multiplied by acceleration.",
            "One British imperial gallon equals approximately four and a half liters.",
            "The gravitational potential energy equals mass times gravitational acceleration times height.",
            "A complete geometric circle equals three hundred and sixty angular degrees.",
            "In classical microeconomics price equals marginal cost under perfect market competition.",
            "One astronomical unit approximately equals ninety-three million miles from Earth to the Sun.",
            "The electric current in an ohmic circuit equals voltage divided by resistance.",
            "In formal logic a proposition equals its double negation under classical principles.",
            "The perimeter of an equilateral triangle equals three times the length of any side.",
            "The total weight of the cargo equals the sum of all individual freight pallets.",
            "The kinetic energy of a moving projectile equals one-half its mass times velocity squared.",
            "True social progress equals ensuring equal opportunities for every citizen.",
            "In democratic theory political legitimacy equals the consent of the governed.",
            "She believes that genuine happiness equals having meaningful work and loving companionship.",
            "For the explorer reaching the summit equals the culmination of a lifelong dream.",
            "In our household mutual respect equals listening with patience and kindness.",
            "His personal philosophy equals treating every stranger with dignity and empathy.",
            "To the environmentalist protecting ancient forests equals preserving future generations.",
            "In modern civil rights all citizens are recognized as equals before the law.",
            "She treated all members of her diverse research laboratory as respected professional equals.",
            "The founding constitutional charter proclaimed that all human beings are born equal.",
            "They competed on the tournament tennis court as formidable athletic equals.",
            "The two diplomatic delegations sat across the conference table as sovereign equals.",
            "He regarded his scientific colleagues as intellectual equals whose opinions he valued.",
            "The democratic constitution guarantees that all votes carry equal weight in elections.",
            "Equal access to clean drinking water is recognized as a fundamental human right.",
            "The treaty established an equal partnership between the two border municipalities.",
            "Equal pay for equal work remains an enduring principle of workplace fairness.",
            "Both candidates participated in the televised debate on completely equal terms.",
            "The educational trust strives to provide equal educational opportunities to all districts.",
            "The inheritance was partitioned into three strictly equal shares among the siblings.",
            "The match ended in a draw when both soccer teams scored equal goals at full time.",
            "The balance scale remained perfectly level because both brass pans held equal weights.",
            "The recipe requires equal proportions of dark cocoa powder and confectioner sugar.",
            "The two musical compositions were of equal artistic brilliance and emotional depth.",
            "The marathon runners crossed the finish line in equal times down to the hundredth.",
            "The judge awarded equal joint custody of the children to both loving parents.",
            "Both competing proposals demonstrated equal merit during the comprehensive technical review.",
            "The divided highway allocated equal lanes to northbound and southbound commuters.",
            "The twin oak trees grew to equal heights on opposite sides of the garden gate.",
            "The two historic clock towers struck the midday hour with equal resonant volume.",
            // Category: Casing (50 cases)
            "The camel case is made of genuine full-grain leather imported from Morocco.",
            "She bought a sturdy camel case to protect her brass binoculars during safari.",
            "The antique camel case exhibited fine hand-stitched leather seams along the handles.",
            "A snake case was found near the garden wall where reptile eggs had hatched.",
            "The wildlife rescuer opened the ventilated snake case to examine the rescued python.",
            "A custom padded snake case was built for safely transporting exotic reptiles to the zoo.",
            "The legal scholar studied the constant case law surrounding maritime boundaries.",
            "The lawyer cited a constant case from nineteen twenty-five as an authoritative precedent.",
            "Her constant case of seasonal allergies made springtime outdoor gardening difficult.",
            "His constant case of mistaken identity became an amusing recurring joke among friends.",
            "We discussed camel case during our team meeting on graphic design standards.",
            "The fashion designer displayed a tailored camel coat and a matching camel case.",
            "A leather craftsman repaired the brass latches on the vintage camel case luggage.",
            "The zookeeper placed the harmless garter snake into the portable snake case.",
            "A glass-fronted snake case was installed inside the university herpetology museum.",
            "The lawyer argued that the constant case precedent supported the plaintiffs claim.",
            "The medical journal documented a rare and constant case of nocturnal hyperhidrosis.",
            "The traveler carried a lightweight camel case containing watercolor brushes and sketchbooks.",
            "The museum curator cleaned the dust from the nineteenth-century camel case trunk.",
            "The wildlife sanctuary manufactured a temperature-regulated snake case for venomous vipers.",
            "The vintage camera was stored securely inside a fitted camel case with velvet lining.",
            "She packed her antique porcelain tea set inside a padded camel case for shipping.",
            "The biological surveyor carried an aluminum snake case into the tropical wetlands.",
            "The herpetologist designed a secure snake case with double-locking acrylic latches.",
            "A constant case of hiccups interrupted his speech to the delight of the audience.",
            "The legal precedent was established through a constant case of maritime salvage disputes.",
            "The saddle maker crafted a bespoke camel case for desert expedition survival equipment.",
            "The antique shop on the corner sold an authentic Victorian camel case vanity box.",
            "The reptile enthusiast purchased a heated snake case for his captive-bred corn snakes.",
            "The wildlife documentary crew loaded their specialized snake case into the off-road vehicle.",
            "The judge noted that this was a constant case of municipal regulatory noncompliance.",
            "The equestrian team loaded their leather grooming kit into a polished camel case.",
            "The museum acquired a rare nomadic camel case used by Tuareg caravaneers in the Sahara.",
            "The zoo veterinarian transported the injured timber rattlesnake in a reinforced snake case.",
            "The court reporter documented a constant case of procedural objections from the defense.",
            "Her camel case briefcase was a graduation gift from her grandparents after law school.",
            "The leather artisan embossed geometric rosettes onto the lid of the camel case.",
            "A snake case equipped with temperature telemetry sensors was placed in the incubator.",
            "The historical precedent was reinforced by a constant case of judicial consensus.",
            "The traveling illusionist kept his props inside a mysterious brass-bound camel case.",
            "The reptile exhibit featured a bioactive snake case with living moss and damp bark.",
            "A constant case of mild vertigo troubled the mountaineer during high-altitude ascents.",
            "The vintage luggage set included a matching steamer trunk and a handheld camel case.",
            "The herpetological society published guidelines on safe snake case construction standards.",
            "The district attorney referenced a constant case of appellate court rulings on bail.",
            "The caravan guide fastened the water-resistant camel case to the wooden pack saddle.",
            "The wildlife handler demonstrated how to safely open an emergency snake case.",
            "The continuous rain created a constant case of dampness throughout the stone cottage.",
            "He stored his collection of vintage coins inside an insulated camel case vault.",
            "The wildlife rescue team arrived at the suburban residence equipped with a snake case.",
            // Category: ApiDatabaseRepo (50 cases)
            "The ancient Roman town of Api was an important agricultural trading center.",
            "The Api valley in northern Italy is famous for terraced vineyards and apple orchards.",
            "The botanical name Apium graveolens refers to wild aromatic wetland celery.",
            "Local beekeepers belong to the county apicultural society which studies the genus Apis.",
            "The museum holds an ancient bronze coin stamped with the sacred sacred Apis bull.",
            "The database of historical weather observations stretches back more than two centuries.",
            "An international database of bird migration sightings is maintained by volunteers.",
            "The university library hosts a searchable database of digitized medieval manuscripts.",
            "A national database of rare genetic variants helped clinicians identify the diagnosis.",
            "The maritime database tracks container vessel movements across global shipping lanes.",
            "The genealogical database allowed her to trace ancestors who arrived in Boston in eighteen forty.",
            "A comprehensive database of botanical plant specimens was completed by the herbarium.",
            "The public health database monitors influenza infection rates across regional clinics.",
            "The patent database contains millions of technical inventions dating back to the eighteenth century.",
            "A shared database of seismic tremors provides early warnings for earthquake response teams.",
            "The wildlife conservation database maps the territorial boundaries of endangered wolves.",
            "The municipal property database lists building permits and historical zoning changes.",
            "The astronomical database catalogues the spectral characteristics of nearby stars.",
            "A global database of sea surface temperatures showed consistent ocean warming trends.",
            "The forensic database matched ballistic striations from the recovered cartridge case.",
            "The library acts as a repository of historical community documents and town charters.",
            "The seed vault in Norway is a secure global repository of crop biodiversity.",
            "The national museum serves as a repository for valuable pre-Columbian gold artifacts.",
            "Her grandmother was a living repository of traditional folklore and herbal medicine.",
            "The municipal archives operate as the primary repository for historical land deeds.",
            "The biological repository preserves cryopreserved stem cell lines for regenerative research.",
            "An underground geological repository was designed for long-term safe isolation of waste.",
            "The university art repository houses thousands of prints by Japanese woodblock masters.",
            "The county historical society serves as a trusted repository of oral history recordings.",
            "The digital repository preserves high-resolution scans of fragile illuminated manuscripts.",
            "The herbarium repository contains over two million pressed and dried botanical specimens.",
            "The national sound archive is a sonic repository of indigenous music and spoken dialects.",
            "A secure geological repository in the granite bedrock was surveyed by mining engineers.",
            "The institute repository collects peer-reviewed research publications from all faculty.",
            "The church crypt functioned as a solemn repository for ancestral family sarcophagi.",
            "The central data repository receives meteorological telemetry from eighty mountain weather stations.",
            "The historical library was a repository of rare navigational maps drawn by Portuguese cartographers.",
            "The oceanographic institute repository preserves deep-sea sediment cores extracted from trenches.",
            "A state repository of legal statutes and executive orders is accessible to all citizens online.",
            "The museum storage facility is a climate-controlled repository for fragile renaissance tapestries.",
            "The town clerk entered the newly registered birth certificate into the municipal database.",
            "Researchers analyzed the extensive climate database to measure changes in seasonal precipitation.",
            "The university library expanded its digital repository of open-access doctoral dissertations.",
            "The historical repository was established by a generous philanthropic endowment in nineteen fifty.",
            "The blood bank database tracks available supplies of rare negative blood groups daily.",
            "The botanical repository loaned specimens of endangered alpine ferns to the foreign university.",
            "The museum repository was fortified against earthquake tremors using base-isolation bearings.",
            "The astronomical database recorded the orbital coordinates of newly detected near-Earth asteroids.",
            "An international repository of viral genome sequences facilitated rapid vaccine development.",
            "The national library repository protects original handwritten drafts of classic American novels.",
            // Category: PathTerminal (50 cases)
            "The winding stone path led upward through fragrant pine groves toward the mountain chapel.",
            "The garden path was paved with smooth gray river pebbles bordered by flowering lavender.",
            "A narrow coastal path winds along the towering chalk cliffs overlooking the stormy English Channel.",
            "The forest path was covered in a soft thick blanket of fallen golden autumn leaves.",
            "The paved bicycle path connects suburban residential neighborhoods directly to the city center.",
            "She walked along the gravel path that meandered beside the tranquil babbling trout stream.",
            "The mountain path became steep and rocky as the expedition approached the alpine pass.",
            "A brick path encircled the central historic fountain in the sunlit public square.",
            "The woodland path was shaded by ancient canopy trees of white oak and sugar maple.",
            "Follow the marked nature path to observe native migratory songbirds in their wetland habitat.",
            "The sandy path crossed over the coastal dunes via an elevated wooden boardwalk structure.",
            "The historical cobblestone path was laid by Roman soldiers during the first century.",
            "The dirt path through the meadow was worn smooth by generations of grazing dairy cattle.",
            "A private stone path connected the main colonial residence to the organic vegetable greenhouse.",
            "The switchback path climbed two thousand vertical feet up the face of the granite cliff.",
            "The jogging path around the urban lake is illuminated by energy-efficient solar lanterns.",
            "The shaded path provided welcome relief from the blazing midsummer Mediterranean sun.",
            "The scenic path followed the historic railway right-of-way through dramatic mountain gorges.",
            "The lantern-lit path guided evening dinner guests through the fragrant Japanese tea garden.",
            "The ancient pilgrimage path traverses over five hundred miles across northern Spain.",
            "The ferry terminal was bustling with morning commuters carrying briefcases and coffee.",
            "A new international terminal was inaugurated at the airport to accommodate wide-body airliners.",
            "The central bus terminal is located adjacent to the intercity railway passenger station.",
            "The oil terminal at the deepwater seaport can dock three supertankers simultaneously.",
            "The cruise ship terminal features customs processing facilities for four thousand passengers.",
            "The freight terminal handles dozens of container trains arriving from the west coast ports.",
            "The passenger terminal had soaring glass ceilings that filled the departures concourse with sunlight.",
            "The electrical terminal on the storage battery was corroded and needed wire brushing.",
            "The train arrived at the final terminal station five minutes ahead of published schedule.",
            "The airline operates thirty domestic departure gates from terminal two at Chicago.",
            "The shipping terminal utilizes automated gantry cranes to unload maritime container vessels.",
            "The subway terminal features underground pedestrian tunnels connecting to the commercial district.",
            "The airport terminal had comfortable waiting lounges equipped with wireless charging stations.",
            "The marine terminal was protected from winter ocean swells by a massive stone breakwater.",
            "The grain terminal transferred fifty thousand bushels of hard red winter wheat into the barge.",
            "The modern passenger terminal includes quiet meditation rooms and designated children play areas.",
            "The railway terminal building was restored to its original nineteenth-century beaux-arts grandeur.",
            "The container terminal operates around the clock under high-intensity LED floodlights.",
            "The bus terminal waiting room was heated by a large cast-iron radiator beneath the window.",
            "The commuter ferry docked smoothly alongside slip four at the downtown maritime terminal.",
            "The hiker paused along the mountain path to admire the panoramic sunrise over the valley.",
            "The botanical garden path wound between vibrant rhododendrons and towering bamboo groves.",
            "The terminal illness was managed with compassionate palliative care and family presence.",
            "The battery terminal was securely clamped with a brass nut to prevent intermittent electrical faults.",
            "The airport terminal renovation added ten automated passport control kiosks for international arrivals.",
            "The cargo terminal was surrounded by secure perimeter fencing with infrared surveillance.",
            "The historic footpath across the private agricultural estate has been protected by public right-of-way.",
            "The railway terminal concourse reverberated with the rhythmic echoes of departing locomotive whistles.",
            "The paved path through the park was cleared of winter snow by municipal utility vehicles.",
            "The ferry terminal ticket counter opened thirty minutes before the scheduled dawn sailing.",
            // Category: AtPhrases (50 cases)
            "She decided to stay at home during the severe winter blizzard with a good book.",
            "He was working at home yesterday because the downtown office heating was being repaired.",
            "The children were learning at home during the unexpected three-day snowstorm closure.",
            "She loves cooking hearty vegetable soups when spending quiet Sunday evenings at home.",
            "We celebrated my grandmother ninetieth birthday with a festive family dinner at home.",
            "He works at home on Mondays and Fridays under the flexible hybrid employment agreement.",
            "The elderly patient recovered much faster when receiving specialized physical therapy at home.",
            "She felt completely at home among the warm and hospitable villagers in the mountain valley.",
            "He was at work early this morning to prepare the laboratory for the chemical titration.",
            "She remained at work until seven in the evening to finalize the international client brief.",
            "He met his future wife while they were both working as young interns at work.",
            "The safety inspector observed several exemplary ergonomic practices while at work today.",
            "She had to stay at work late to supervise the overnight software server data migration.",
            "He had an urgent phone conversation with his family while taking a brief break at work.",
            "The employees enjoyed a catered Mexican luncheon while at work celebrating the company anniversary.",
            "She keeps a framed photograph of her golden retriever on her desk while at work.",
            "The children arrived at school wearing their bright yellow waterproof raincoats.",
            "He studied classical Latin and ancient Greek when he was a dedicated student at school.",
            "The parent-teacher association organized an autumn fundraising bake sale at school.",
            "She won first prize in the regional science fair held at school last spring.",
            "He was elected president of the student council during his final senior year at school.",
            "The sports field at school was freshly painted with white lines for the soccer tournament.",
            "She made lifelong friends during her formative four years living in the dormitory at school.",
            "The children performed a delightful holiday musical for their proud parents at school.",
            "He was not at the office when the courier arrived with the urgent legal envelope.",
            "She arrived at the office just in time for the nine oclock executive briefing.",
            "The conference room at the office was equipped with high-definition video conferencing screens.",
            "He left his reading glasses behind at the office and had to return after hours.",
            "The air conditioning at the office malfunctioned during the hottest afternoon of July.",
            "She keeps a spare blazer and a pair of sensible walking shoes at the office.",
            "The team met at the office cafeteria to discuss the upcoming product launch timeline.",
            "He was working quietly at the office on Saturday morning when the phone suddenly rang.",
            "The stars shone with breathtaking brilliance at night in the remote desert canyon.",
            "The temperature drops significantly at night in high-altitude desert ecosystems.",
            "The owl hunted silently for field mice under the pale moonlight at night.",
            "He enjoys listening to classical string quartets on the balcony late at night.",
            "The coastal lighthouse flashed its white beam every ten seconds throughout at night.",
            "The solar clock in the palace courtyard casts its shortest shadow exactly at noon.",
            "The church bells rang twelve resonant chimes when the clock hands aligned at noon.",
            "The outdoor construction workers paused for a wholesome packed lunch at noon.",
            "The market square reaches its peak level of energetic human activity at noon.",
            "The rooster crowed from atop the wooden fencepost promptly at dawn.",
            "The fishing trawlers departed the harbor under a pastel pink sky at dawn.",
            "The dew on the spiderweb glistened like tiny diamonds in the first light at dawn.",
            "The deer emerged from the dense oak forest to drink from the stream at dawn.",
            "The streetlights flickered on automatically as daylight faded rapidly at dusk.",
            "The bats left their roost in the abandoned barn to hunt nocturnal insects at dusk.",
            "The evening breeze brought the sweet fragrance of night-blooming jasmine at dusk.",
            "The campfire was kindled as temperatures began their steady decline at dusk.",
            "The sky transformed into a dramatic canvas of violet and burnished gold at dusk.",
        };

        foreach (var s in sentences)
        {
            yield return new object[] { s };
        }
    }

    [Theory]
    [MemberData(nameof(CuratedAdversarialProseCases))]
    public void AdversarialProse_NeverTriggersDeveloperTransformations(string proseSentence)
    {
        string output = _pipeline.Format(proseSentence, ProseOptions);

        Assert.False(output.Contains("=>"), $"Output contains unwanted '=>': {output}");
        Assert.False(output.Contains("->"), $"Output contains unwanted '->': {output}");
        Assert.False(output.Contains("=="), $"Output contains unwanted '==': {output}");
        Assert.False(output.Contains("!="), $"Output contains unwanted '!=': {output}");
        Assert.False(Regex.IsMatch(output, @"(?<![A-Za-z0-9])_[A-Za-z0-9]"), $"Output contains unwanted '_': {output}");
        Assert.False(Regex.IsMatch(output, @"[a-z]+[A-Z][a-zA-Z0-9]*"), $"Output contains unwanted camelCase: {output}");
        Assert.False(output.Contains('@') && !proseSentence.Contains('@'), $"Output contains unwanted '@': {output}");
    }

    [Fact]
    public void AdversarialProse_TotalCaseCount_IsAtLeast500()
    {
        int count = 0;
        foreach (var _ in CuratedAdversarialProseCases()) count++;
        Assert.True(count >= 500, $"Corpus must contain at least 500 cases, found {count}");
    }
}
