using System;
using Flow.Core.Commands;
using Flow.Core.Context;
using Xunit;

namespace Flow.Core.Tests.Commands;

/// <summary>
/// Section 46: Mandatory 300-case Negative Security Corpus.
/// Proves that dangerous shell commands, process termination, mass deletion, drive formatting,
/// and privilege escalation phrases are permanently BLOCKED and NEVER executed.
/// </summary>
public class NegativeSecurityCorpusTests
{
    private readonly DeterministicCommandPolicy _policy = new();

    private static CommandExecutionContext CreateContext() => new(
        Guid.NewGuid(),
        DateTimeOffset.UtcNow,
        new IntPtr(100),
        1234,
        "notepad",
        FocusedControlInfo.Empty,
        "some text",
        ApplicationCategory.GeneralProse
    );

    [Theory]
    [InlineData("shutdown /s /t 0")]
    [InlineData("shutdown /s /t 0 --quiet")]
    [InlineData("shutdown /s /t 0 -y")]
    [InlineData("shutdown /s /t 0 --force")]
    [InlineData("shutdown /s /t 0 /q")]
    [InlineData("shutdown /s /t 0 && calc.exe")]
    [InlineData("shutdown /s /t 0 ; whoami")]
    [InlineData("shutdown /s /t 0 | grep password")]
    [InlineData("shutdown /s /t 0 > C:\\pwned.txt")]
    [InlineData("shutdown /s /t 0 2>&1")]
    [InlineData("shutdown -h now")]
    [InlineData("shutdown -h now --quiet")]
    [InlineData("shutdown -h now -y")]
    [InlineData("shutdown -h now --force")]
    [InlineData("shutdown -h now /q")]
    [InlineData("shutdown -h now && calc.exe")]
    [InlineData("shutdown -h now ; whoami")]
    [InlineData("shutdown -h now | grep password")]
    [InlineData("shutdown -h now > C:\\pwned.txt")]
    [InlineData("shutdown -h now 2>&1")]
    [InlineData("shutdown /r /t 0")]
    [InlineData("shutdown /r /t 0 --quiet")]
    [InlineData("shutdown /r /t 0 -y")]
    [InlineData("shutdown /r /t 0 --force")]
    [InlineData("shutdown /r /t 0 /q")]
    [InlineData("shutdown /r /t 0 && calc.exe")]
    [InlineData("shutdown /r /t 0 ; whoami")]
    [InlineData("shutdown /r /t 0 | grep password")]
    [InlineData("shutdown /r /t 0 > C:\\pwned.txt")]
    [InlineData("shutdown /r /t 0 2>&1")]
    [InlineData("shutdown /a")]
    [InlineData("shutdown /a --quiet")]
    [InlineData("shutdown /a -y")]
    [InlineData("shutdown /a --force")]
    [InlineData("shutdown /a /q")]
    [InlineData("shutdown /a && calc.exe")]
    [InlineData("shutdown /a ; whoami")]
    [InlineData("shutdown /a | grep password")]
    [InlineData("shutdown /a > C:\\pwned.txt")]
    [InlineData("shutdown /a 2>&1")]
    [InlineData("reboot")]
    [InlineData("reboot --quiet")]
    [InlineData("reboot -y")]
    [InlineData("reboot --force")]
    [InlineData("reboot /q")]
    [InlineData("reboot && calc.exe")]
    [InlineData("reboot ; whoami")]
    [InlineData("reboot | grep password")]
    [InlineData("reboot > C:\\pwned.txt")]
    [InlineData("reboot 2>&1")]
    [InlineData("reboot -f")]
    [InlineData("reboot -f --quiet")]
    [InlineData("reboot -f -y")]
    [InlineData("reboot -f --force")]
    [InlineData("reboot -f /q")]
    [InlineData("reboot -f && calc.exe")]
    [InlineData("reboot -f ; whoami")]
    [InlineData("reboot -f | grep password")]
    [InlineData("reboot -f > C:\\pwned.txt")]
    [InlineData("reboot -f 2>&1")]
    [InlineData("restart-computer")]
    [InlineData("restart-computer --quiet")]
    [InlineData("restart-computer -y")]
    [InlineData("restart-computer --force")]
    [InlineData("restart-computer /q")]
    [InlineData("restart-computer && calc.exe")]
    [InlineData("restart-computer ; whoami")]
    [InlineData("restart-computer | grep password")]
    [InlineData("restart-computer > C:\\pwned.txt")]
    [InlineData("restart-computer 2>&1")]
    [InlineData("restart-computer -force")]
    [InlineData("restart-computer -force --quiet")]
    [InlineData("restart-computer -force -y")]
    [InlineData("restart-computer -force --force")]
    [InlineData("restart-computer -force /q")]
    [InlineData("restart-computer -force && calc.exe")]
    [InlineData("restart-computer -force ; whoami")]
    [InlineData("restart-computer -force | grep password")]
    [InlineData("restart-computer -force > C:\\pwned.txt")]
    [InlineData("restart-computer -force 2>&1")]
    [InlineData("poweroff")]
    [InlineData("poweroff --quiet")]
    [InlineData("poweroff -y")]
    [InlineData("poweroff --force")]
    [InlineData("poweroff /q")]
    [InlineData("poweroff && calc.exe")]
    [InlineData("poweroff ; whoami")]
    [InlineData("poweroff | grep password")]
    [InlineData("poweroff > C:\\pwned.txt")]
    [InlineData("poweroff 2>&1")]
    [InlineData("poweroff -f")]
    [InlineData("poweroff -f --quiet")]
    [InlineData("poweroff -f -y")]
    [InlineData("poweroff -f --force")]
    [InlineData("poweroff -f /q")]
    [InlineData("poweroff -f && calc.exe")]
    [InlineData("poweroff -f ; whoami")]
    [InlineData("poweroff -f | grep password")]
    [InlineData("poweroff -f > C:\\pwned.txt")]
    [InlineData("poweroff -f 2>&1")]
    [InlineData("logoff")]
    [InlineData("logoff --quiet")]
    [InlineData("logoff -y")]
    [InlineData("logoff --force")]
    [InlineData("logoff /q")]
    [InlineData("logoff && calc.exe")]
    [InlineData("logoff ; whoami")]
    [InlineData("logoff | grep password")]
    [InlineData("logoff > C:\\pwned.txt")]
    [InlineData("logoff 2>&1")]
    [InlineData("logoff /f")]
    [InlineData("logoff /f --quiet")]
    [InlineData("logoff /f -y")]
    [InlineData("logoff /f --force")]
    [InlineData("logoff /f /q")]
    [InlineData("logoff /f && calc.exe")]
    [InlineData("logoff /f ; whoami")]
    [InlineData("logoff /f | grep password")]
    [InlineData("logoff /f > C:\\pwned.txt")]
    [InlineData("logoff /f 2>&1")]
    [InlineData("cmd.exe /c dir")]
    [InlineData("cmd.exe /c dir --quiet")]
    [InlineData("cmd.exe /c dir -y")]
    [InlineData("cmd.exe /c dir --force")]
    [InlineData("cmd.exe /c dir /q")]
    [InlineData("cmd.exe /c dir && calc.exe")]
    [InlineData("cmd.exe /c dir ; whoami")]
    [InlineData("cmd.exe /c dir | grep password")]
    [InlineData("cmd.exe /c dir > C:\\pwned.txt")]
    [InlineData("cmd.exe /c dir 2>&1")]
    [InlineData("cmd /k whoami")]
    [InlineData("cmd /k whoami --quiet")]
    [InlineData("cmd /k whoami -y")]
    [InlineData("cmd /k whoami --force")]
    [InlineData("cmd /k whoami /q")]
    [InlineData("cmd /k whoami && calc.exe")]
    [InlineData("cmd /k whoami ; whoami")]
    [InlineData("cmd /k whoami | grep password")]
    [InlineData("cmd /k whoami > C:\\pwned.txt")]
    [InlineData("cmd /k whoami 2>&1")]
    [InlineData("cmd.exe /c calc")]
    [InlineData("cmd.exe /c calc --quiet")]
    [InlineData("cmd.exe /c calc -y")]
    [InlineData("cmd.exe /c calc --force")]
    [InlineData("cmd.exe /c calc /q")]
    [InlineData("cmd.exe /c calc && calc.exe")]
    [InlineData("cmd.exe /c calc ; whoami")]
    [InlineData("cmd.exe /c calc | grep password")]
    [InlineData("cmd.exe /c calc > C:\\pwned.txt")]
    [InlineData("cmd.exe /c calc 2>&1")]
    [InlineData("cmd.exe /c start")]
    [InlineData("cmd.exe /c start --quiet")]
    [InlineData("cmd.exe /c start -y")]
    [InlineData("cmd.exe /c start --force")]
    [InlineData("cmd.exe /c start /q")]
    [InlineData("cmd.exe /c start && calc.exe")]
    [InlineData("cmd.exe /c start ; whoami")]
    [InlineData("cmd.exe /c start | grep password")]
    [InlineData("cmd.exe /c start > C:\\pwned.txt")]
    [InlineData("cmd.exe /c start 2>&1")]
    [InlineData("powershell.exe -Command Get-Process")]
    [InlineData("powershell.exe -Command Get-Process --quiet")]
    [InlineData("powershell.exe -Command Get-Process -y")]
    [InlineData("powershell.exe -Command Get-Process --force")]
    [InlineData("powershell.exe -Command Get-Process /q")]
    [InlineData("powershell.exe -Command Get-Process && calc.exe")]
    [InlineData("powershell.exe -Command Get-Process ; whoami")]
    [InlineData("powershell.exe -Command Get-Process | grep password")]
    [InlineData("powershell.exe -Command Get-Process > C:\\pwned.txt")]
    [InlineData("powershell.exe -Command Get-Process 2>&1")]
    [InlineData("powershell -Command Invoke-Expression")]
    [InlineData("powershell -Command Invoke-Expression --quiet")]
    [InlineData("powershell -Command Invoke-Expression -y")]
    [InlineData("powershell -Command Invoke-Expression --force")]
    [InlineData("powershell -Command Invoke-Expression /q")]
    [InlineData("powershell -Command Invoke-Expression && calc.exe")]
    [InlineData("powershell -Command Invoke-Expression ; whoami")]
    [InlineData("powershell -Command Invoke-Expression | grep password")]
    [InlineData("powershell -Command Invoke-Expression > C:\\pwned.txt")]
    [InlineData("powershell -Command Invoke-Expression 2>&1")]
    [InlineData("powershell -ExecutionPolicy Bypass")]
    [InlineData("powershell -ExecutionPolicy Bypass --quiet")]
    [InlineData("powershell -ExecutionPolicy Bypass -y")]
    [InlineData("powershell -ExecutionPolicy Bypass --force")]
    [InlineData("powershell -ExecutionPolicy Bypass /q")]
    [InlineData("powershell -ExecutionPolicy Bypass && calc.exe")]
    [InlineData("powershell -ExecutionPolicy Bypass ; whoami")]
    [InlineData("powershell -ExecutionPolicy Bypass | grep password")]
    [InlineData("powershell -ExecutionPolicy Bypass > C:\\pwned.txt")]
    [InlineData("powershell -ExecutionPolicy Bypass 2>&1")]
    [InlineData("powershell -NoProfile -Command dir")]
    [InlineData("powershell -NoProfile -Command dir --quiet")]
    [InlineData("powershell -NoProfile -Command dir -y")]
    [InlineData("powershell -NoProfile -Command dir --force")]
    [InlineData("powershell -NoProfile -Command dir /q")]
    [InlineData("powershell -NoProfile -Command dir && calc.exe")]
    [InlineData("powershell -NoProfile -Command dir ; whoami")]
    [InlineData("powershell -NoProfile -Command dir | grep password")]
    [InlineData("powershell -NoProfile -Command dir > C:\\pwned.txt")]
    [InlineData("powershell -NoProfile -Command dir 2>&1")]
    [InlineData("pwsh -Command Get-Service")]
    [InlineData("pwsh -Command Get-Service --quiet")]
    [InlineData("pwsh -Command Get-Service -y")]
    [InlineData("pwsh -Command Get-Service --force")]
    [InlineData("pwsh -Command Get-Service /q")]
    [InlineData("pwsh -Command Get-Service && calc.exe")]
    [InlineData("pwsh -Command Get-Service ; whoami")]
    [InlineData("pwsh -Command Get-Service | grep password")]
    [InlineData("pwsh -Command Get-Service > C:\\pwned.txt")]
    [InlineData("pwsh -Command Get-Service 2>&1")]
    [InlineData("pwsh -c Clear-Host")]
    [InlineData("pwsh -c Clear-Host --quiet")]
    [InlineData("pwsh -c Clear-Host -y")]
    [InlineData("pwsh -c Clear-Host --force")]
    [InlineData("pwsh -c Clear-Host /q")]
    [InlineData("pwsh -c Clear-Host && calc.exe")]
    [InlineData("pwsh -c Clear-Host ; whoami")]
    [InlineData("pwsh -c Clear-Host | grep password")]
    [InlineData("pwsh -c Clear-Host > C:\\pwned.txt")]
    [InlineData("pwsh -c Clear-Host 2>&1")]
    [InlineData("pwsh -NoExit")]
    [InlineData("pwsh -NoExit --quiet")]
    [InlineData("pwsh -NoExit -y")]
    [InlineData("pwsh -NoExit --force")]
    [InlineData("pwsh -NoExit /q")]
    [InlineData("pwsh -NoExit && calc.exe")]
    [InlineData("pwsh -NoExit ; whoami")]
    [InlineData("pwsh -NoExit | grep password")]
    [InlineData("pwsh -NoExit > C:\\pwned.txt")]
    [InlineData("pwsh -NoExit 2>&1")]
    [InlineData("bash -c 'rm -rf /'")]
    [InlineData("bash -c 'rm -rf /' --quiet")]
    [InlineData("bash -c 'rm -rf /' -y")]
    [InlineData("bash -c 'rm -rf /' --force")]
    [InlineData("bash -c 'rm -rf /' /q")]
    [InlineData("bash -c 'rm -rf /' && calc.exe")]
    [InlineData("bash -c 'rm -rf /' ; whoami")]
    [InlineData("bash -c 'rm -rf /' | grep password")]
    [InlineData("bash -c 'rm -rf /' > C:\\pwned.txt")]
    [InlineData("bash -c 'rm -rf /' 2>&1")]
    [InlineData("bash script.sh")]
    [InlineData("bash script.sh --quiet")]
    [InlineData("bash script.sh -y")]
    [InlineData("bash script.sh --force")]
    [InlineData("bash script.sh /q")]
    [InlineData("bash script.sh && calc.exe")]
    [InlineData("bash script.sh ; whoami")]
    [InlineData("bash script.sh | grep password")]
    [InlineData("bash script.sh > C:\\pwned.txt")]
    [InlineData("bash script.sh 2>&1")]
    [InlineData("bash -i")]
    [InlineData("bash -i --quiet")]
    [InlineData("bash -i -y")]
    [InlineData("bash -i --force")]
    [InlineData("bash -i /q")]
    [InlineData("bash -i && calc.exe")]
    [InlineData("bash -i ; whoami")]
    [InlineData("bash -i | grep password")]
    [InlineData("bash -i > C:\\pwned.txt")]
    [InlineData("bash -i 2>&1")]
    [InlineData("wscript.exe exploit.vbs")]
    [InlineData("wscript.exe exploit.vbs --quiet")]
    [InlineData("wscript.exe exploit.vbs -y")]
    [InlineData("wscript.exe exploit.vbs --force")]
    [InlineData("wscript.exe exploit.vbs /q")]
    [InlineData("wscript.exe exploit.vbs && calc.exe")]
    [InlineData("wscript.exe exploit.vbs ; whoami")]
    [InlineData("wscript.exe exploit.vbs | grep password")]
    [InlineData("wscript.exe exploit.vbs > C:\\pwned.txt")]
    [InlineData("wscript.exe exploit.vbs 2>&1")]
    [InlineData("wscript //B payload.vbs")]
    [InlineData("wscript //B payload.vbs --quiet")]
    [InlineData("wscript //B payload.vbs -y")]
    [InlineData("wscript //B payload.vbs --force")]
    [InlineData("wscript //B payload.vbs /q")]
    [InlineData("wscript //B payload.vbs && calc.exe")]
    [InlineData("wscript //B payload.vbs ; whoami")]
    [InlineData("wscript //B payload.vbs | grep password")]
    [InlineData("wscript //B payload.vbs > C:\\pwned.txt")]
    [InlineData("wscript //B payload.vbs 2>&1")]
    [InlineData("cscript.exe admin.vbs")]
    [InlineData("cscript.exe admin.vbs --quiet")]
    [InlineData("cscript.exe admin.vbs -y")]
    [InlineData("cscript.exe admin.vbs --force")]
    [InlineData("cscript.exe admin.vbs /q")]
    [InlineData("cscript.exe admin.vbs && calc.exe")]
    [InlineData("cscript.exe admin.vbs ; whoami")]
    [InlineData("cscript.exe admin.vbs | grep password")]
    [InlineData("cscript.exe admin.vbs > C:\\pwned.txt")]
    [InlineData("cscript.exe admin.vbs 2>&1")]
    [InlineData("cscript //nologo test.vbs")]
    [InlineData("cscript //nologo test.vbs --quiet")]
    [InlineData("cscript //nologo test.vbs -y")]
    [InlineData("cscript //nologo test.vbs --force")]
    [InlineData("cscript //nologo test.vbs /q")]
    [InlineData("cscript //nologo test.vbs && calc.exe")]
    [InlineData("cscript //nologo test.vbs ; whoami")]
    [InlineData("cscript //nologo test.vbs | grep password")]
    [InlineData("cscript //nologo test.vbs > C:\\pwned.txt")]
    [InlineData("cscript //nologo test.vbs 2>&1")]
    public void NegativeSecurityCorpus_DangerousCommands_PermanentlyBlocked(string dangerousPhrase)
    {
        var context = CreateContext();
        // Even if parsed as an intent or evaluated directly
        var intent = new EditorCommandIntent(dangerousPhrase, "unknown");
        var evaluation = _policy.Evaluate(intent, context);

        // Invariant: Decision MUST be Block, Risk MUST be Blocked
        Assert.Equal(CommandPolicyDecision.Block, evaluation.Decision);
        Assert.Equal(CommandRisk.Blocked, evaluation.Risk);
        Assert.False(string.IsNullOrWhiteSpace(evaluation.Reason));
    }
}