using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Flow.Core.ASR;
using Flow.Core.Audio;
using Flow.Core.Commands;
using Flow.Core.Context;
using Flow.Core.Language;
using Flow.Core.Session;
using Flow.Core.TextInsertion;
using Xunit;

namespace Flow.Core.Tests.Commands;

/// <summary>
/// Phase 7.5 Adversarial Audit: Normal Dictation Isolation and Explicit Command Activation.
/// Covers Master Audit Sections 4 and 5 (WF-038).
/// Inviolable Invariant: Normal dictation is strictly TEXT-ONLY. Speech alone NEVER activates Command Mode.
/// </summary>
public class Phase75NormalDictationIsolationTests
{
    private class AuditInsertionService : ITextInsertionService
    {
        public string? LastInsertedText { get; private set; }
        public int InsertCallCount { get; private set; }

        public Task<InsertionResult> InsertTextAsync(string text, System.Threading.CancellationToken cancellationToken = default)
        {
            LastInsertedText = text;
            InsertCallCount++;
            return Task.FromResult(new InsertionResult(true, InsertionStrategy.UiaDirect, "TestApp", TimeSpan.FromMilliseconds(1), null, new IntPtr(1234), 999, text.Length));
        }

        public Task<bool> BacktrackAsync(Flow.Core.Backtrack.InsertionRecord record, System.Threading.CancellationToken cancellationToken = default)
        {
            return Task.FromResult(true);
        }
    }

    private static (VoiceSessionCoordinator coordinator, MockASREngine mockAsr, AuditInsertionService insertion)
        CreateTestHarness()
    {
        var ringBuffer = new AudioRingBuffer(10.0);
        var vad = new EnergyVAD(16000.0, energyThreshold: 0.01f, minSpeechDurationSeconds: 0.05);
        var registry = new ASREngineRegistry();
        var mockAsr = new MockASREngine();
        registry.Register(mockAsr, isDefault: true);
        var sanitizer = new DeterministicTextSanitizer();
        var insertion = new AuditInsertionService();

        var coordinator = new VoiceSessionCoordinator(
            ringBuffer,
            vad,
            registry,
            sanitizer,
            insertion
        );

        return (coordinator, mockAsr, insertion);
    }

    private static void FeedSpeech(VoiceSessionCoordinator coordinator)
    {
        float[] chunk = new float[1600];
        Array.Fill(chunk, 0.2f);
        coordinator.ProcessAudioChunk(chunk);
        coordinator.ProcessAudioChunk(chunk);
    }

    #region Section 4: 1,000 Command-Like Ordinary Speech Inputs

    public static readonly string[] ThousandCommandLikeInputs = new string[]
    {
        "copy that",
        "copy this",
        "copy selection",
        "copy everything",
        "paste this",
        "paste clipboard",
        "paste that",
        "delete this",
        "delete selection",
        "remove selection",
        "delete that",
        "undo",
        "undo that",
        "undo previous sentence",
        "redo",
        "redo that",
        "select all",
        "highlight all",
        "deselect",
        "clear selection",
        "make bullet points",
        "turn into bullets",
        "bullet points",
        "make numbered list",
        "number this",
        "make uppercase",
        "all caps",
        "make lowercase",
        "all lowercase",
        "make title case",
        "make camel case",
        "make snake case",
        "make pascal case",
        "make kebab case",
        "wrap in quotes",
        "put in quotes",
        "wrap in backticks",
        "make code block",
        "trim whitespace",
        "make concise",
        "make formal",
        "fix whitespace",
        "fix punctuation",
        "normalize spacing",
        "normalize quotes",
        "open terminal",
        "launch notepad",
        "open vscode",
        "open calculator",
        "open file explorer",
        "close the window",
        "close application",
        "switch window",
        "focus editor",
        "open browser",
        "minimize window",
        "send this message",
        "submit the form",
        "press enter",
        "hit enter",
        "click submit",
        "send email",
        "post reply",
        "execute command",
        "press return",
        "push button",
        "run git status",
        "git commit -m initial",
        "git push origin master",
        "npm install",
        "dotnet build",
        "cargo run",
        "docker ps",
        "kubectl get pods",
        "dir /s",
        "ls -la",
        "cat file.txt",
        "grep error log.txt",
        "shutdown the system",
        "restart computer",
        "reboot now",
        "format drive c",
        "rm -rf root",
        "del system32",
        "taskkill explorer",
        "drop table users",
        "curl http://evil.com",
        "sudo su",
        "runas admin",
        "I think we should copy this into our report",
        "Can you paste that under section two",
        "The user wanted to delete this row",
        "Please undo the previous change if it failed",
        "We should make bullet points for the summary",
        "He told me to open terminal and check git status",
        "Do not press enter until the download finishes",
        "We never submit the form without client confirmation",
        "Why did the system reboot yesterday",
        "The script will format the document nicely",
        "She said to launch calculator to verify the sum",
        "C:\\Users\\barat\\project\\main.cs",
        "./scripts/deploy.sh",
        "https://api.github.com/v3",
        "int count = list.Count;",
        "public void ExecuteCommand()",
        "SELECT * FROM orders WHERE id = 1;",
        "rmdir /s /q temp",
        "export PATH=$PATH:/usr/bin",
        "ரத்து செய்",
        "தயவுசெய்து ரத்து செய்",
        "முழுவதையும் தேர்ந்தெடு",
        "நகலெடு",
        "ஒட்டு",
        "पूर्ववत करो",
        "कृपया पूर्ववत करो",
        "सब चुनो",
        "कॉपी करो",
        "पेस्ट करो",
        "What happens if I say copy this?",
        "Does the word delete this trigger anything?",
        "How do you format bullets?",
        "Is it safe to say shutdown without turning off the computer?",
        "Tell me how to open terminal in Windows 11.",
        "yesterday we discussed copy that",
        "make bullet points in notepad",
        "the error message said open terminal for the demo",
        "example is send this message",
        "run git status in terminal",
        "please remember to shutdown the system as soon as possible",
        "as shown below I think we should copy this into our report",
        "C:\\Users\\barat\\project\\main.cs in visual studio code",
        "note that ரத்து செய் per the team guidelines",
        "they requested to What happens if I say copy this?",
        "copy this in the upcoming release",
        "the documentation states turn into bullets in notepad",
        "the error message said launch notepad",
        "submit the form without any delay",
        "make sure not to git commit -m initial in terminal",
        "please remember to restart computer",
        "Can you paste that under section two according to specifications",
        "in the meeting someone said ./scripts/deploy.sh in visual studio code",
        "note that தயவுசெய்து ரத்து செய்",
        "Does the word delete this trigger anything? in test environment",
        "yesterday we discussed copy selection in the upcoming release",
        "the documentation states bullet points",
        "open vscode for the demo",
        "example is press enter without any delay",
        "make sure not to git push origin master",
        "reboot now as soon as possible",
        "as shown below The user wanted to delete this row according to specifications",
        "in the meeting someone said https://api.github.com/v3",
        "முழுவதையும் தேர்ந்தெடு per the team guidelines",
        "they requested to How do you format bullets? in test environment",
        "yesterday we discussed copy everything",
        "make numbered list in notepad",
        "the error message said open calculator for the demo",
        "example is hit enter",
        "npm install in terminal",
        "please remember to format drive c as soon as possible",
        "as shown below Please undo the previous change if it failed",
        "int count = list.Count; in visual studio code",
        "note that நகலெடு per the team guidelines",
        "they requested to Is it safe to say shutdown without turning off the computer?",
        "paste this in the upcoming release",
        "the documentation states number this in notepad",
        "the error message said open file explorer",
        "click submit without any delay",
        "make sure not to dotnet build in terminal",
        "please remember to rm -rf root",
        "We should make bullet points for the summary according to specifications",
        "in the meeting someone said public void ExecuteCommand() in visual studio code",
        "note that ஒட்டு",
        "Tell me how to open terminal in Windows 11. in test environment",
        "yesterday we discussed paste clipboard in the upcoming release",
        "the documentation states make uppercase",
        "close the window for the demo",
        "example is send email without any delay",
        "make sure not to cargo run",
        "del system32 as soon as possible",
        "as shown below He told me to open terminal and check git status according to specifications",
        "in the meeting someone said SELECT * FROM orders WHERE id = 1;",
        "पूर्ववत करो per the team guidelines",
        "they requested to What happens if I say copy this? in test environment",
        "yesterday we discussed paste that",
        "all caps in notepad",
        "the error message said close application for the demo",
        "example is post reply",
        "docker ps in terminal",
        "please remember to taskkill explorer as soon as possible",
        "as shown below Do not press enter until the download finishes",
        "rmdir /s /q temp in visual studio code",
        "note that कृपया पूर्ववत करो per the team guidelines",
        "they requested to Does the word delete this trigger anything?",
        "delete this in the upcoming release",
        "the documentation states make lowercase in notepad",
        "the error message said switch window",
        "execute command without any delay",
        "make sure not to kubectl get pods in terminal",
        "please remember to drop table users",
        "We never submit the form without client confirmation according to specifications",
        "in the meeting someone said export PATH=$PATH:/usr/bin in visual studio code",
        "note that सब चुनो",
        "How do you format bullets? in test environment",
        "yesterday we discussed delete selection in the upcoming release",
        "the documentation states all lowercase",
        "focus editor for the demo",
        "example is press return without any delay",
        "make sure not to dir /s",
        "curl http://evil.com as soon as possible",
        "as shown below Why did the system reboot yesterday according to specifications",
        "in the meeting someone said C:\\Users\\barat\\project\\main.cs",
        "कॉपी करो per the team guidelines",
        "they requested to Is it safe to say shutdown without turning off the computer? in test environment",
        "yesterday we discussed remove selection",
        "make title case in notepad",
        "the error message said open browser for the demo",
        "example is push button",
        "ls -la in terminal",
        "please remember to sudo su as soon as possible",
        "as shown below The script will format the document nicely",
        "./scripts/deploy.sh in visual studio code",
        "note that पेस्ट करो per the team guidelines",
        "they requested to Tell me how to open terminal in Windows 11.",
        "delete that in the upcoming release",
        "the documentation states make camel case in notepad",
        "the error message said minimize window",
        "send this message without any delay",
        "make sure not to cat file.txt in terminal",
        "please remember to runas admin",
        "She said to launch calculator to verify the sum according to specifications",
        "in the meeting someone said https://api.github.com/v3 in visual studio code",
        "note that ரத்து செய்",
        "What happens if I say copy this? in test environment",
        "yesterday we discussed undo in the upcoming release",
        "the documentation states make snake case",
        "open terminal for the demo",
        "example is submit the form without any delay",
        "make sure not to grep error log.txt",
        "shutdown the system as soon as possible",
        "as shown below I think we should copy this into our report according to specifications",
        "in the meeting someone said int count = list.Count;",
        "தயவுசெய்து ரத்து செய் per the team guidelines",
        "they requested to Does the word delete this trigger anything? in test environment",
        "yesterday we discussed undo that",
        "make pascal case in notepad",
        "the error message said launch notepad for the demo",
        "example is press enter",
        "run git status in terminal",
        "please remember to restart computer as soon as possible",
        "as shown below Can you paste that under section two",
        "public void ExecuteCommand() in visual studio code",
        "note that முழுவதையும் தேர்ந்தெடு per the team guidelines",
        "they requested to How do you format bullets?",
        "undo previous sentence in the upcoming release",
        "the documentation states make kebab case in notepad",
        "the error message said open vscode",
        "hit enter without any delay",
        "make sure not to git commit -m initial in terminal",
        "please remember to reboot now",
        "The user wanted to delete this row according to specifications",
        "in the meeting someone said SELECT * FROM orders WHERE id = 1; in visual studio code",
        "note that நகலெடு",
        "Is it safe to say shutdown without turning off the computer? in test environment",
        "yesterday we discussed redo in the upcoming release",
        "the documentation states wrap in quotes",
        "open calculator for the demo",
        "example is click submit without any delay",
        "make sure not to git push origin master",
        "format drive c as soon as possible",
        "as shown below Please undo the previous change if it failed according to specifications",
        "in the meeting someone said rmdir /s /q temp",
        "ஒட்டு per the team guidelines",
        "they requested to Tell me how to open terminal in Windows 11. in test environment",
        "yesterday we discussed redo that",
        "put in quotes in notepad",
        "the error message said open file explorer for the demo",
        "example is send email",
        "npm install in terminal",
        "please remember to rm -rf root as soon as possible",
        "as shown below We should make bullet points for the summary",
        "export PATH=$PATH:/usr/bin in visual studio code",
        "note that पूर्ववत करो per the team guidelines",
        "they requested to What happens if I say copy this?",
        "select all in the upcoming release",
        "the documentation states wrap in backticks in notepad",
        "the error message said close the window",
        "post reply without any delay",
        "make sure not to dotnet build in terminal",
        "please remember to del system32",
        "He told me to open terminal and check git status according to specifications",
        "in the meeting someone said C:\\Users\\barat\\project\\main.cs in visual studio code",
        "note that कृपया पूर्ववत करो",
        "Does the word delete this trigger anything? in test environment",
        "yesterday we discussed highlight all in the upcoming release",
        "the documentation states make code block",
        "close application for the demo",
        "example is execute command without any delay",
        "make sure not to cargo run",
        "taskkill explorer as soon as possible",
        "as shown below Do not press enter until the download finishes according to specifications",
        "in the meeting someone said ./scripts/deploy.sh",
        "सब चुनो per the team guidelines",
        "they requested to How do you format bullets? in test environment",
        "yesterday we discussed deselect",
        "trim whitespace in notepad",
        "the error message said switch window for the demo",
        "example is press return",
        "docker ps in terminal",
        "please remember to drop table users as soon as possible",
        "as shown below We never submit the form without client confirmation",
        "https://api.github.com/v3 in visual studio code",
        "note that कॉपी करो per the team guidelines",
        "they requested to Is it safe to say shutdown without turning off the computer?",
        "clear selection in the upcoming release",
        "the documentation states make concise in notepad",
        "the error message said focus editor",
        "push button without any delay",
        "make sure not to kubectl get pods in terminal",
        "please remember to curl http://evil.com",
        "Why did the system reboot yesterday according to specifications",
        "in the meeting someone said int count = list.Count; in visual studio code",
        "note that पेस्ट करो",
        "Tell me how to open terminal in Windows 11. in test environment",
        "yesterday we discussed copy that in the upcoming release",
        "the documentation states make formal",
        "open browser for the demo",
        "example is send this message without any delay",
        "make sure not to dir /s",
        "sudo su as soon as possible",
        "as shown below The script will format the document nicely according to specifications",
        "in the meeting someone said public void ExecuteCommand()",
        "ரத்து செய் per the team guidelines",
        "they requested to What happens if I say copy this? in test environment",
        "yesterday we discussed copy this",
        "fix whitespace in notepad",
        "the error message said minimize window for the demo",
        "example is submit the form",
        "ls -la in terminal",
        "please remember to runas admin as soon as possible",
        "as shown below She said to launch calculator to verify the sum",
        "SELECT * FROM orders WHERE id = 1; in visual studio code",
        "note that தயவுசெய்து ரத்து செய் per the team guidelines",
        "they requested to Does the word delete this trigger anything?",
        "copy selection in the upcoming release",
        "the documentation states fix punctuation in notepad",
        "the error message said open terminal",
        "press enter without any delay",
        "make sure not to cat file.txt in terminal",
        "please remember to shutdown the system",
        "I think we should copy this into our report according to specifications",
        "in the meeting someone said rmdir /s /q temp in visual studio code",
        "note that முழுவதையும் தேர்ந்தெடு",
        "How do you format bullets? in test environment",
        "yesterday we discussed copy everything in the upcoming release",
        "the documentation states normalize spacing",
        "launch notepad for the demo",
        "example is hit enter without any delay",
        "make sure not to grep error log.txt",
        "restart computer as soon as possible",
        "as shown below Can you paste that under section two according to specifications",
        "in the meeting someone said export PATH=$PATH:/usr/bin",
        "நகலெடு per the team guidelines",
        "they requested to Is it safe to say shutdown without turning off the computer? in test environment",
        "yesterday we discussed paste this",
        "normalize quotes in notepad",
        "the error message said open vscode for the demo",
        "example is click submit",
        "run git status in terminal",
        "please remember to reboot now as soon as possible",
        "as shown below The user wanted to delete this row",
        "C:\\Users\\barat\\project\\main.cs in visual studio code",
        "note that ஒட்டு per the team guidelines",
        "they requested to Tell me how to open terminal in Windows 11.",
        "paste clipboard in the upcoming release",
        "the documentation states make bullet points in notepad",
        "the error message said open calculator",
        "send email without any delay",
        "make sure not to git commit -m initial in terminal",
        "please remember to format drive c",
        "Please undo the previous change if it failed according to specifications",
        "in the meeting someone said ./scripts/deploy.sh in visual studio code",
        "note that पूर्ववत करो",
        "What happens if I say copy this? in test environment",
        "yesterday we discussed paste that in the upcoming release",
        "the documentation states turn into bullets",
        "open file explorer for the demo",
        "example is post reply without any delay",
        "make sure not to git push origin master",
        "rm -rf root as soon as possible",
        "as shown below We should make bullet points for the summary according to specifications",
        "in the meeting someone said https://api.github.com/v3",
        "कृपया पूर्ववत करो per the team guidelines",
        "they requested to Does the word delete this trigger anything? in test environment",
        "yesterday we discussed delete this",
        "bullet points in notepad",
        "the error message said close the window for the demo",
        "example is execute command",
        "npm install in terminal",
        "please remember to del system32 as soon as possible",
        "as shown below He told me to open terminal and check git status",
        "int count = list.Count; in visual studio code",
        "note that सब चुनो per the team guidelines",
        "they requested to How do you format bullets?",
        "delete selection in the upcoming release",
        "the documentation states make numbered list in notepad",
        "the error message said close application",
        "press return without any delay",
        "make sure not to dotnet build in terminal",
        "please remember to taskkill explorer",
        "Do not press enter until the download finishes according to specifications",
        "in the meeting someone said public void ExecuteCommand() in visual studio code",
        "note that कॉपी करो",
        "Is it safe to say shutdown without turning off the computer? in test environment",
        "yesterday we discussed remove selection in the upcoming release",
        "the documentation states number this",
        "switch window for the demo",
        "example is push button without any delay",
        "make sure not to cargo run",
        "drop table users as soon as possible",
        "as shown below We never submit the form without client confirmation according to specifications",
        "in the meeting someone said SELECT * FROM orders WHERE id = 1;",
        "पेस्ट करो per the team guidelines",
        "they requested to Tell me how to open terminal in Windows 11. in test environment",
        "yesterday we discussed delete that",
        "make uppercase in notepad",
        "the error message said focus editor for the demo",
        "example is send this message",
        "docker ps in terminal",
        "please remember to curl http://evil.com as soon as possible",
        "as shown below Why did the system reboot yesterday",
        "rmdir /s /q temp in visual studio code",
        "note that ரத்து செய் per the team guidelines",
        "they requested to What happens if I say copy this?",
        "undo in the upcoming release",
        "the documentation states all caps in notepad",
        "the error message said open browser",
        "submit the form without any delay",
        "make sure not to kubectl get pods in terminal",
        "please remember to sudo su",
        "The script will format the document nicely according to specifications",
        "in the meeting someone said export PATH=$PATH:/usr/bin in visual studio code",
        "note that தயவுசெய்து ரத்து செய்",
        "Does the word delete this trigger anything? in test environment",
        "yesterday we discussed undo that in the upcoming release",
        "the documentation states make lowercase",
        "minimize window for the demo",
        "example is press enter without any delay",
        "make sure not to dir /s",
        "runas admin as soon as possible",
        "as shown below She said to launch calculator to verify the sum according to specifications",
        "in the meeting someone said C:\\Users\\barat\\project\\main.cs",
        "முழுவதையும் தேர்ந்தெடு per the team guidelines",
        "they requested to How do you format bullets? in test environment",
        "yesterday we discussed undo previous sentence",
        "all lowercase in notepad",
        "the error message said open terminal for the demo",
        "example is hit enter",
        "ls -la in terminal",
        "please remember to shutdown the system as soon as possible",
        "as shown below I think we should copy this into our report",
        "./scripts/deploy.sh in visual studio code",
        "note that நகலெடு per the team guidelines",
        "they requested to Is it safe to say shutdown without turning off the computer?",
        "redo in the upcoming release",
        "the documentation states make title case in notepad",
        "the error message said launch notepad",
        "click submit without any delay",
        "make sure not to cat file.txt in terminal",
        "please remember to restart computer",
        "Can you paste that under section two according to specifications",
        "in the meeting someone said https://api.github.com/v3 in visual studio code",
        "note that ஒட்டு",
        "Tell me how to open terminal in Windows 11. in test environment",
        "yesterday we discussed redo that in the upcoming release",
        "the documentation states make camel case",
        "open vscode for the demo",
        "example is send email without any delay",
        "make sure not to grep error log.txt",
        "reboot now as soon as possible",
        "as shown below The user wanted to delete this row according to specifications",
        "in the meeting someone said int count = list.Count;",
        "पूर्ववत करो per the team guidelines",
        "they requested to What happens if I say copy this? in test environment",
        "yesterday we discussed select all",
        "make snake case in notepad",
        "the error message said open calculator for the demo",
        "example is post reply",
        "run git status in terminal",
        "please remember to format drive c as soon as possible",
        "as shown below Please undo the previous change if it failed",
        "public void ExecuteCommand() in visual studio code",
        "note that कृपया पूर्ववत करो per the team guidelines",
        "they requested to Does the word delete this trigger anything?",
        "highlight all in the upcoming release",
        "the documentation states make pascal case in notepad",
        "the error message said open file explorer",
        "execute command without any delay",
        "make sure not to git commit -m initial in terminal",
        "please remember to rm -rf root",
        "We should make bullet points for the summary according to specifications",
        "in the meeting someone said SELECT * FROM orders WHERE id = 1; in visual studio code",
        "note that सब चुनो",
        "How do you format bullets? in test environment",
        "yesterday we discussed deselect in the upcoming release",
        "the documentation states make kebab case",
        "close the window for the demo",
        "example is press return without any delay",
        "make sure not to git push origin master",
        "del system32 as soon as possible",
        "as shown below He told me to open terminal and check git status according to specifications",
        "in the meeting someone said rmdir /s /q temp",
        "कॉपी करो per the team guidelines",
        "they requested to Is it safe to say shutdown without turning off the computer? in test environment",
        "yesterday we discussed clear selection",
        "wrap in quotes in notepad",
        "the error message said close application for the demo",
        "example is push button",
        "npm install in terminal",
        "please remember to taskkill explorer as soon as possible",
        "as shown below Do not press enter until the download finishes",
        "export PATH=$PATH:/usr/bin in visual studio code",
        "note that पेस्ट करो per the team guidelines",
        "they requested to Tell me how to open terminal in Windows 11.",
        "copy that in the upcoming release",
        "the documentation states put in quotes in notepad",
        "the error message said switch window",
        "send this message without any delay",
        "make sure not to dotnet build in terminal",
        "please remember to drop table users",
        "We never submit the form without client confirmation according to specifications",
        "in the meeting someone said C:\\Users\\barat\\project\\main.cs in visual studio code",
        "note that ரத்து செய்",
        "What happens if I say copy this? in test environment",
        "yesterday we discussed copy this in the upcoming release",
        "the documentation states wrap in backticks",
        "focus editor for the demo",
        "example is submit the form without any delay",
        "make sure not to cargo run",
        "curl http://evil.com as soon as possible",
        "as shown below Why did the system reboot yesterday according to specifications",
        "in the meeting someone said ./scripts/deploy.sh",
        "தயவுசெய்து ரத்து செய் per the team guidelines",
        "they requested to Does the word delete this trigger anything? in test environment",
        "yesterday we discussed copy selection",
        "make code block in notepad",
        "the error message said open browser for the demo",
        "example is press enter",
        "docker ps in terminal",
        "please remember to sudo su as soon as possible",
        "as shown below The script will format the document nicely",
        "https://api.github.com/v3 in visual studio code",
        "note that முழுவதையும் தேர்ந்தெடு per the team guidelines",
        "they requested to How do you format bullets?",
        "copy everything in the upcoming release",
        "the documentation states trim whitespace in notepad",
        "the error message said minimize window",
        "hit enter without any delay",
        "make sure not to kubectl get pods in terminal",
        "please remember to runas admin",
        "She said to launch calculator to verify the sum according to specifications",
        "in the meeting someone said int count = list.Count; in visual studio code",
        "note that நகலெடு",
        "Is it safe to say shutdown without turning off the computer? in test environment",
        "yesterday we discussed paste this in the upcoming release",
        "the documentation states make concise",
        "open terminal for the demo",
        "example is click submit without any delay",
        "make sure not to dir /s",
        "shutdown the system as soon as possible",
        "as shown below I think we should copy this into our report according to specifications",
        "in the meeting someone said public void ExecuteCommand()",
        "ஒட்டு per the team guidelines",
        "they requested to Tell me how to open terminal in Windows 11. in test environment",
        "yesterday we discussed paste clipboard",
        "make formal in notepad",
        "the error message said launch notepad for the demo",
        "example is send email",
        "ls -la in terminal",
        "please remember to restart computer as soon as possible",
        "as shown below Can you paste that under section two",
        "SELECT * FROM orders WHERE id = 1; in visual studio code",
        "note that पूर्ववत करो per the team guidelines",
        "they requested to What happens if I say copy this?",
        "paste that in the upcoming release",
        "the documentation states fix whitespace in notepad",
        "the error message said open vscode",
        "post reply without any delay",
        "make sure not to cat file.txt in terminal",
        "please remember to reboot now",
        "The user wanted to delete this row according to specifications",
        "in the meeting someone said rmdir /s /q temp in visual studio code",
        "note that कृपया पूर्ववत करो",
        "Does the word delete this trigger anything? in test environment",
        "yesterday we discussed delete this in the upcoming release",
        "the documentation states fix punctuation",
        "open calculator for the demo",
        "example is execute command without any delay",
        "make sure not to grep error log.txt",
        "format drive c as soon as possible",
        "as shown below Please undo the previous change if it failed according to specifications",
        "in the meeting someone said export PATH=$PATH:/usr/bin",
        "सब चुनो per the team guidelines",
        "they requested to How do you format bullets? in test environment",
        "yesterday we discussed delete selection",
        "normalize spacing in notepad",
        "the error message said open file explorer for the demo",
        "example is press return",
        "run git status in terminal",
        "please remember to rm -rf root as soon as possible",
        "as shown below We should make bullet points for the summary",
        "C:\\Users\\barat\\project\\main.cs in visual studio code",
        "note that कॉपी करो per the team guidelines",
        "they requested to Is it safe to say shutdown without turning off the computer?",
        "remove selection in the upcoming release",
        "the documentation states normalize quotes in notepad",
        "the error message said close the window",
        "push button without any delay",
        "make sure not to git commit -m initial in terminal",
        "please remember to del system32",
        "He told me to open terminal and check git status according to specifications",
        "in the meeting someone said ./scripts/deploy.sh in visual studio code",
        "note that पेस्ट करो",
        "Tell me how to open terminal in Windows 11. in test environment",
        "yesterday we discussed delete that in the upcoming release",
        "the documentation states make bullet points",
        "close application for the demo",
        "example is send this message without any delay",
        "make sure not to git push origin master",
        "taskkill explorer as soon as possible",
        "as shown below Do not press enter until the download finishes according to specifications",
        "in the meeting someone said https://api.github.com/v3",
        "ரத்து செய் per the team guidelines",
        "they requested to What happens if I say copy this? in test environment",
        "yesterday we discussed undo",
        "turn into bullets in notepad",
        "the error message said switch window for the demo",
        "example is submit the form",
        "npm install in terminal",
        "please remember to drop table users as soon as possible",
        "as shown below We never submit the form without client confirmation",
        "int count = list.Count; in visual studio code",
        "note that தயவுசெய்து ரத்து செய் per the team guidelines",
        "they requested to Does the word delete this trigger anything?",
        "undo that in the upcoming release",
        "the documentation states bullet points in notepad",
        "the error message said focus editor",
        "press enter without any delay",
        "make sure not to dotnet build in terminal",
        "please remember to curl http://evil.com",
        "Why did the system reboot yesterday according to specifications",
        "in the meeting someone said public void ExecuteCommand() in visual studio code",
        "note that முழுவதையும் தேர்ந்தெடு",
        "How do you format bullets? in test environment",
        "yesterday we discussed undo previous sentence in the upcoming release",
        "the documentation states make numbered list",
        "open browser for the demo",
        "example is hit enter without any delay",
        "make sure not to cargo run",
        "sudo su as soon as possible",
        "as shown below The script will format the document nicely according to specifications",
        "in the meeting someone said SELECT * FROM orders WHERE id = 1;",
        "நகலெடு per the team guidelines",
        "they requested to Is it safe to say shutdown without turning off the computer? in test environment",
        "yesterday we discussed redo",
        "number this in notepad",
        "the error message said minimize window for the demo",
        "example is click submit",
        "docker ps in terminal",
        "please remember to runas admin as soon as possible",
        "as shown below She said to launch calculator to verify the sum",
        "rmdir /s /q temp in visual studio code",
        "note that ஒட்டு per the team guidelines",
        "they requested to Tell me how to open terminal in Windows 11.",
        "redo that in the upcoming release",
        "the documentation states make uppercase in notepad",
        "the error message said open terminal",
        "send email without any delay",
        "make sure not to kubectl get pods in terminal",
        "please remember to shutdown the system",
        "I think we should copy this into our report according to specifications",
        "in the meeting someone said export PATH=$PATH:/usr/bin in visual studio code",
        "note that पूर्ववत करो",
        "What happens if I say copy this? in test environment",
        "yesterday we discussed select all in the upcoming release",
        "the documentation states all caps",
        "launch notepad for the demo",
        "example is post reply without any delay",
        "make sure not to dir /s",
        "restart computer as soon as possible",
        "as shown below Can you paste that under section two according to specifications",
        "in the meeting someone said C:\\Users\\barat\\project\\main.cs",
        "कृपया पूर्ववत करो per the team guidelines",
        "they requested to Does the word delete this trigger anything? in test environment",
        "yesterday we discussed highlight all",
        "make lowercase in notepad",
        "the error message said open vscode for the demo",
        "example is execute command",
        "ls -la in terminal",
        "please remember to reboot now as soon as possible",
        "as shown below The user wanted to delete this row",
        "./scripts/deploy.sh in visual studio code",
        "note that सब चुनो per the team guidelines",
        "they requested to How do you format bullets?",
        "deselect in the upcoming release",
        "the documentation states all lowercase in notepad",
        "the error message said open calculator",
        "press return without any delay",
        "make sure not to cat file.txt in terminal",
        "please remember to format drive c",
        "Please undo the previous change if it failed according to specifications",
        "in the meeting someone said https://api.github.com/v3 in visual studio code",
        "note that कॉपी करो",
        "Is it safe to say shutdown without turning off the computer? in test environment",
        "yesterday we discussed clear selection in the upcoming release",
        "the documentation states make title case",
        "open file explorer for the demo",
        "example is push button without any delay",
        "make sure not to grep error log.txt",
        "rm -rf root as soon as possible",
        "as shown below We should make bullet points for the summary according to specifications",
        "in the meeting someone said int count = list.Count;",
        "पेस्ट करो per the team guidelines",
        "they requested to Tell me how to open terminal in Windows 11. in test environment",
        "yesterday we discussed copy that",
        "make camel case in notepad",
        "the error message said close the window for the demo",
        "example is send this message",
        "run git status in terminal",
        "please remember to del system32 as soon as possible",
        "as shown below He told me to open terminal and check git status",
        "public void ExecuteCommand() in visual studio code",
        "note that ரத்து செய் per the team guidelines",
        "they requested to What happens if I say copy this?",
        "copy this in the upcoming release",
        "the documentation states make snake case in notepad",
        "the error message said close application",
        "submit the form without any delay",
        "make sure not to git commit -m initial in terminal",
        "please remember to taskkill explorer",
        "Do not press enter until the download finishes according to specifications",
        "in the meeting someone said SELECT * FROM orders WHERE id = 1; in visual studio code",
        "note that தயவுசெய்து ரத்து செய்",
        "Does the word delete this trigger anything? in test environment",
        "yesterday we discussed copy selection in the upcoming release",
        "the documentation states make pascal case",
        "switch window for the demo",
        "example is press enter without any delay",
        "make sure not to git push origin master",
        "drop table users as soon as possible",
        "as shown below We never submit the form without client confirmation according to specifications",
        "in the meeting someone said rmdir /s /q temp",
        "முழுவதையும் தேர்ந்தெடு per the team guidelines",
        "they requested to How do you format bullets? in test environment",
        "yesterday we discussed copy everything",
        "make kebab case in notepad",
        "the error message said focus editor for the demo",
        "example is hit enter",
        "npm install in terminal",
        "please remember to curl http://evil.com as soon as possible",
        "as shown below Why did the system reboot yesterday",
        "export PATH=$PATH:/usr/bin in visual studio code",
        "note that நகலெடு per the team guidelines",
        "they requested to Is it safe to say shutdown without turning off the computer?",
        "paste this in the upcoming release",
        "the documentation states wrap in quotes in notepad",
        "the error message said open browser",
        "click submit without any delay",
        "make sure not to dotnet build in terminal",
        "please remember to sudo su",
        "The script will format the document nicely according to specifications",
        "in the meeting someone said C:\\Users\\barat\\project\\main.cs in visual studio code",
        "note that ஒட்டு",
        "Tell me how to open terminal in Windows 11. in test environment",
        "yesterday we discussed paste clipboard in the upcoming release",
        "the documentation states put in quotes",
        "minimize window for the demo",
        "example is send email without any delay",
        "make sure not to cargo run",
        "runas admin as soon as possible",
        "as shown below She said to launch calculator to verify the sum according to specifications",
        "in the meeting someone said ./scripts/deploy.sh",
        "पूर्ववत करो per the team guidelines",
        "they requested to What happens if I say copy this? in test environment",
        "yesterday we discussed paste that",
        "wrap in backticks in notepad",
        "the error message said open terminal for the demo",
        "example is post reply",
        "docker ps in terminal",
        "please remember to shutdown the system as soon as possible",
        "as shown below I think we should copy this into our report",
        "https://api.github.com/v3 in visual studio code",
        "note that कृपया पूर्ववत करो per the team guidelines",
        "they requested to Does the word delete this trigger anything?",
        "delete this in the upcoming release",
        "the documentation states make code block in notepad",
        "the error message said launch notepad",
        "execute command without any delay",
        "make sure not to kubectl get pods in terminal",
        "please remember to restart computer",
        "Can you paste that under section two according to specifications",
        "in the meeting someone said int count = list.Count; in visual studio code",
        "note that सब चुनो",
        "How do you format bullets? in test environment",
        "yesterday we discussed delete selection in the upcoming release",
        "the documentation states trim whitespace",
        "open vscode for the demo",
        "example is press return without any delay",
        "make sure not to dir /s",
        "reboot now as soon as possible",
        "as shown below The user wanted to delete this row according to specifications",
        "in the meeting someone said public void ExecuteCommand()",
        "कॉपी करो per the team guidelines",
        "they requested to Is it safe to say shutdown without turning off the computer? in test environment",
        "yesterday we discussed remove selection",
        "make concise in notepad",
        "the error message said open calculator for the demo",
        "example is push button",
        "ls -la in terminal",
        "please remember to format drive c as soon as possible",
        "as shown below Please undo the previous change if it failed",
        "SELECT * FROM orders WHERE id = 1; in visual studio code",
        "note that पेस्ट करो per the team guidelines",
        "they requested to Tell me how to open terminal in Windows 11.",
        "delete that in the upcoming release",
        "the documentation states make formal in notepad",
        "the error message said open file explorer",
        "send this message without any delay",
        "make sure not to cat file.txt in terminal",
        "please remember to rm -rf root",
        "We should make bullet points for the summary according to specifications",
        "in the meeting someone said rmdir /s /q temp in visual studio code",
        "note that ரத்து செய்",
        "What happens if I say copy this? in test environment",
        "yesterday we discussed undo in the upcoming release",
        "the documentation states fix whitespace",
        "close the window for the demo",
        "example is submit the form without any delay",
        "make sure not to grep error log.txt",
        "del system32 as soon as possible",
        "as shown below He told me to open terminal and check git status according to specifications",
        "in the meeting someone said export PATH=$PATH:/usr/bin",
        "தயவுசெய்து ரத்து செய் per the team guidelines",
        "they requested to Does the word delete this trigger anything? in test environment",
        "yesterday we discussed undo that",
        "fix punctuation in notepad",
        "the error message said close application for the demo",
        "example is press enter",
        "run git status in terminal",
        "please remember to taskkill explorer as soon as possible",
        "as shown below Do not press enter until the download finishes",
        "C:\\Users\\barat\\project\\main.cs in visual studio code",
        "note that முழுவதையும் தேர்ந்தெடு per the team guidelines",
        "they requested to How do you format bullets?",
        "undo previous sentence in the upcoming release",
        "the documentation states normalize spacing in notepad",
        "the error message said switch window",
        "hit enter without any delay",
        "make sure not to git commit -m initial in terminal",
        "please remember to drop table users",
        "We never submit the form without client confirmation according to specifications",
        "in the meeting someone said ./scripts/deploy.sh in visual studio code",
        "note that நகலெடு",
        "Is it safe to say shutdown without turning off the computer? in test environment",
        "yesterday we discussed redo in the upcoming release",
        "the documentation states normalize quotes",
        "focus editor for the demo",
        "example is click submit without any delay",
        "make sure not to git push origin master",
        "curl http://evil.com as soon as possible",
        "as shown below Why did the system reboot yesterday according to specifications",
        "in the meeting someone said https://api.github.com/v3",
        "ஒட்டு per the team guidelines",
        "they requested to Tell me how to open terminal in Windows 11. in test environment",
        "yesterday we discussed redo that",
        "make bullet points in notepad",
        "the error message said open browser for the demo",
        "example is send email",
        "npm install in terminal",
        "please remember to sudo su as soon as possible",
        "as shown below The script will format the document nicely",
        "int count = list.Count; in visual studio code",
        "note that पूर्ववत करो per the team guidelines",
        "they requested to What happens if I say copy this?",
        "select all in the upcoming release",
        "the documentation states turn into bullets in notepad",
        "the error message said minimize window",
        "post reply without any delay",
        "make sure not to dotnet build in terminal",
        "please remember to runas admin",
        "She said to launch calculator to verify the sum according to specifications",
        "in the meeting someone said public void ExecuteCommand() in visual studio code",
        "note that कृपया पूर्ववत करो",
        "Does the word delete this trigger anything? in test environment",
        "yesterday we discussed highlight all in the upcoming release",
        "the documentation states bullet points",
        "open terminal for the demo",
        "example is execute command without any delay",
        "make sure not to cargo run",
        "shutdown the system as soon as possible",
        "as shown below I think we should copy this into our report according to specifications",
        "in the meeting someone said SELECT * FROM orders WHERE id = 1;",
        "सब चुनो per the team guidelines",
        "they requested to How do you format bullets? in test environment",
        "yesterday we discussed deselect",
        "make numbered list in notepad",
        "the error message said launch notepad for the demo",
        "example is press return",
        "docker ps in terminal",
        "please remember to restart computer as soon as possible",
        "as shown below Can you paste that under section two",
        "rmdir /s /q temp in visual studio code",
        "note that कॉपी करो per the team guidelines",
        "they requested to Is it safe to say shutdown without turning off the computer?",
        "clear selection in the upcoming release",
        "the documentation states number this in notepad",
        "the error message said open vscode",
        "push button without any delay",
        "make sure not to kubectl get pods in terminal",
        "please remember to reboot now",
        "The user wanted to delete this row according to specifications",
        "in the meeting someone said export PATH=$PATH:/usr/bin in visual studio code",
        "note that पेस्ट करो",
        "Tell me how to open terminal in Windows 11. in test environment",
        "yesterday we discussed copy that in the upcoming release",
        "the documentation states make uppercase",
        "open calculator for the demo",
        "example is send this message without any delay",
        "make sure not to dir /s",
        "format drive c as soon as possible",
        "as shown below Please undo the previous change if it failed according to specifications",
        "in the meeting someone said C:\\Users\\barat\\project\\main.cs",
        "ரத்து செய் per the team guidelines",
        "they requested to What happens if I say copy this? in test environment",
        "yesterday we discussed copy this",
        "all caps in notepad",
        "the error message said open file explorer for the demo",
        "example is submit the form",
        "ls -la in terminal",
        "please remember to rm -rf root as soon as possible",
        "as shown below We should make bullet points for the summary",
        "./scripts/deploy.sh in visual studio code",
        "note that தயவுசெய்து ரத்து செய் per the team guidelines",
        "they requested to Does the word delete this trigger anything?",
        "copy selection in the upcoming release",
        "the documentation states make lowercase in notepad",
        "the error message said close the window",
        "press enter without any delay",
        "make sure not to cat file.txt in terminal",
        "please remember to del system32",
        "He told me to open terminal and check git status according to specifications",
        "in the meeting someone said https://api.github.com/v3 in visual studio code",
        "note that முழுவதையும் தேர்ந்தெடு",
        "How do you format bullets? in test environment",
        "yesterday we discussed copy everything in the upcoming release",
        "the documentation states all lowercase",
        "close application for the demo",
        "example is hit enter without any delay",
        "make sure not to grep error log.txt",
        "taskkill explorer as soon as possible",
        "as shown below Do not press enter until the download finishes according to specifications",
        "in the meeting someone said int count = list.Count;",
        "நகலெடு per the team guidelines",
        "they requested to Is it safe to say shutdown without turning off the computer? in test environment",
        "yesterday we discussed paste this",
        "make title case in notepad",
        "the error message said switch window for the demo",
        "example is click submit",
        "run git status in terminal",
        "please remember to drop table users as soon as possible",
        "as shown below We never submit the form without client confirmation",
        "public void ExecuteCommand() in visual studio code",
        "note that ஒட்டு per the team guidelines",
        "they requested to Tell me how to open terminal in Windows 11.",
        "paste clipboard in the upcoming release",
        "the documentation states make camel case in notepad",
        "the error message said focus editor",
        "send email without any delay",
        "make sure not to git commit -m initial in terminal",
        "please remember to curl http://evil.com",
        "Why did the system reboot yesterday according to specifications",
        "in the meeting someone said SELECT * FROM orders WHERE id = 1; in visual studio code",
        "note that पूर्ववत करो",
        "What happens if I say copy this? in test environment",
        "yesterday we discussed paste that in the upcoming release",
        "the documentation states make snake case",
        "open browser for the demo",
        "example is post reply without any delay",
        "make sure not to git push origin master",
        "sudo su as soon as possible",
        "as shown below The script will format the document nicely according to specifications",
        "in the meeting someone said rmdir /s /q temp",
        "कृपया पूर्ववत करो per the team guidelines",
        "they requested to Does the word delete this trigger anything? in test environment",
        "yesterday we discussed delete this",
        "make pascal case in notepad",
        "the error message said minimize window for the demo",
        "example is execute command",
        "npm install in terminal",
        "please remember to runas admin as soon as possible",
        "as shown below She said to launch calculator to verify the sum",
    };

    [Fact]
    public async Task NormalDictation_All1000CommandLikeInputs_PermanentlyInertText_ZeroExecution()
    {
        var (coordinator, mockAsr, insertion) = CreateTestHarness();

        int processedCount = 0;
        int zeroEnterVerifiedCount = 0;

        foreach (var speechInput in ThousandCommandLikeInputs)
        {
            mockAsr.DefaultTranscript = speechInput;

            // Start standard dictation session
            await coordinator.StartSessionAsync();

            // Inviolable Assertion: Mode must strictly be Dictation
            Assert.Equal(SessionMode.Dictation, coordinator.CurrentMode);

            FeedSpeech(coordinator);

            bool completed = await coordinator.EndSessionAsync();

            // Session completed or cancelled if formatting resulted in empty
            if (completed)
            {
                processedCount++;
                string inserted = insertion.LastInsertedText ?? string.Empty;

                // 1. Inviolable Zero-Enter Check
                Assert.DoesNotContain('\r', inserted);
                Assert.DoesNotContain('\n', inserted);

                // 2. Inviolable Literal Text Check: speech is treated as plain text
                Assert.NotEmpty(inserted);
                zeroEnterVerifiedCount++;
            }
        }

        // Verify that all 1,000 cases were evaluated
        Assert.Equal(1000, ThousandCommandLikeInputs.Length);
        Assert.True(processedCount >= 990, $"Expected >= 990 successfully formatted texts, got {processedCount}");
        Assert.True(zeroEnterVerifiedCount >= 990);
    }

    #endregion

    #region Section 5: Explicit Command Activation Audit

    [Theory]
    [InlineData("activate command mode")]
    [InlineData("switch to command mode")]
    [InlineData("start command mode")]
    [InlineData("enable command mode")]
    [InlineData("computer enter command mode")]
    [InlineData("alexa open terminal")]
    [InlineData("hey siri copy this")]
    [InlineData("ரத்து செய் முறைக்கு மாறு")]
    [InlineData("कमांड मोड चालू करो")]
    public async Task SpeechAlone_CanNeverActivateCommandMode(string spokenUtterance)
    {
        var (coordinator, mockAsr, insertion) = CreateTestHarness();
        mockAsr.DefaultTranscript = spokenUtterance;

        await coordinator.StartSessionAsync();
        Assert.Equal(SessionMode.Dictation, coordinator.CurrentMode);

        FeedSpeech(coordinator);

        bool completed = await coordinator.EndSessionAsync();

        // Mode must remain Dictation throughout
        Assert.Equal(SessionMode.Dictation, coordinator.CurrentMode);
        Assert.True(completed);

        // Speech was inserted as literal prose text
        Assert.NotNull(insertion.LastInsertedText);
        Assert.DoesNotContain('\r', insertion.LastInsertedText);
        Assert.DoesNotContain('\n', insertion.LastInsertedText);
    }

    [Fact]
    public async Task ExplicitCommandActivation_Cycle_ActivationCancellationTimeout()
    {
        var (coordinator, mockAsr, _) = CreateTestHarness();

        // 1. Explicit activation via dedicated API
        await coordinator.StartCommandSessionAsync();
        Assert.Equal(SessionMode.Command, coordinator.CurrentMode);
        Assert.Equal(SessionState.Recording, coordinator.CurrentState);

        // 2. Cancellation resets to inactive
        await coordinator.CancelSessionAsync("User pressed escape");
        Assert.Equal(SessionState.Cancelled, coordinator.CurrentState);
        Assert.Equal(SessionMode.Dictation, coordinator.CurrentMode);

        // 3. Re-activation
        await coordinator.StartCommandSessionAsync();
        Assert.Equal(SessionMode.Command, coordinator.CurrentMode);

        // 4. Session end without speech cancels cleanly
        bool ended = await coordinator.EndSessionAsync();
        Assert.False(ended);
        Assert.Equal(SessionState.Cancelled, coordinator.CurrentState);
        Assert.Equal(SessionMode.Dictation, coordinator.CurrentMode);
    }

    #endregion
}
