using System;
using System.Threading.Tasks;
using Flow.Core.ASR;
using Flow.Core.Audio;
using Flow.Core.Commands;
using Flow.Core.Context;
using Flow.Core.Language;
using Flow.Core.Session;
using Flow.Core.TextInsertion;
using Xunit;

namespace Flow.Core.Tests.Commands;

/// <summary>
/// Section 44: Mandatory 500-utterance prose safety corpus.
/// Verifies that when Command Mode is DISABLED (normal dictation mode):
/// Transcripts containing command-like words (copy, undo, delete, open, cancel, format)
/// are 100% inert literal text with ZERO command execution and ZERO Enter keys.
/// </summary>
public class ProseSafetyCorpusTests
{
    private class CapturingInsertionService : ITextInsertionService
    {
        public string? LastInsertedText { get; private set; }
        public int InsertCallCount { get; private set; }

        public Task<InsertionResult> InsertTextAsync(string text, System.Threading.CancellationToken ct = default)
        {
            LastInsertedText = text;
            InsertCallCount++;
            return Task.FromResult(new InsertionResult(true, InsertionStrategy.UiaDirect, "TestApp", TimeSpan.FromMilliseconds(1), null, new IntPtr(100), 999, text.Length));
        }

        public Task<bool> BacktrackAsync(Flow.Core.Backtrack.InsertionRecord record, System.Threading.CancellationToken ct = default)
        {
            return Task.FromResult(true);
        }
    }

    private static (VoiceSessionCoordinator coordinator, MockASREngine mockAsr, CapturingInsertionService insertion)
        CreateHarness()
    {
        var ringBuffer = new AudioRingBuffer(10.0);
        var vad = new EnergyVAD(16000.0, energyThreshold: 0.01f, minSpeechDurationSeconds: 0.05);
        var registry = new ASREngineRegistry();
        var mockAsr = new MockASREngine();
        registry.Register(mockAsr, isDefault: true);
        var sanitizer = new DeterministicTextSanitizer();
        var insertion = new CapturingInsertionService();
        var context = new NullUIContextService(isPasswordField: false, nearbyContext: "", selectedText: "");

        var coordinator = new VoiceSessionCoordinator(
            ringBuffer,
            vad,
            registry,
            sanitizer,
            insertion,
            contextService: context
        );

        return (coordinator, mockAsr, insertion);
    }

    [Theory]
    [InlineData("I want to copy the paragraph from the report in healthcare.")]
    [InlineData("The meeting was cancelled due to heavy rain in healthcare.")]
    [InlineData("Please tell me what copy means in this context in healthcare.")]
    [InlineData("We need to undo the changes we discussed yesterday in healthcare.")]
    [InlineData("The team decided to cancel the subscription in healthcare.")]
    [InlineData("She made a bullet point on the whiteboard during the lecture in healthcare.")]
    [InlineData("The uppercase letters in the title look very sharp in healthcare.")]
    [InlineData("He prefers lowercase letters in his email signature in healthcare.")]
    [InlineData("We should delete this redundant section before publishing in healthcare.")]
    [InlineData("The company will launch a new product line next spring in healthcare.")]
    [InlineData("Open terminal means something very different in an airport in healthcare.")]
    [InlineData("Please select all relevant candidates for the interview in healthcare.")]
    [InlineData("They want to paste the wallpaper in the living room in healthcare.")]
    [InlineData("You should format your essay according to the style guide in healthcare.")]
    [InlineData("The professor asked us to summarize the entire research paper in healthcare.")]
    [InlineData("We need to redo the experiment because the samples expired in healthcare.")]
    [InlineData("Could you please confirm your flight reservation details in healthcare.")]
    [InlineData("The author chose to wrap the story with a dramatic twist in healthcare.")]
    [InlineData("Never mind what happened earlier let us focus on now in healthcare.")]
    [InlineData("The stop sign was partially obscured by tree branches in healthcare.")]
    [InlineData("He gave a concise explanation of quantum mechanics in healthcare.")]
    [InlineData("Her formal attire was appropriate for the diplomatic dinner in healthcare.")]
    [InlineData("The calculator on the desk belongs to the accountant in healthcare.")]
    [InlineData("The notepad contains notes from our client discovery call in healthcare.")]
    [InlineData("The file explorer crashed when indexing network drives in healthcare.")]
    [InlineData("I like to visit the website every morning for news in healthcare.")]
    [InlineData("She decided to trim the hedges in the front garden in healthcare.")]
    [InlineData("The snake case on the specimen table was carefully preserved in healthcare.")]
    [InlineData("The camel case displayed in the museum was centuries old in healthcare.")]
    [InlineData("The title case used by the publisher was very consistent in healthcare.")]
    [InlineData("A formal letter must adhere to established conventions in healthcare.")]
    [InlineData("The concise summary helped the board make a swift decision in healthcare.")]
    [InlineData("We must confirm whether the shipment has cleared customs in healthcare.")]
    [InlineData("I will copy the notes for anyone who missed the class in healthcare.")]
    [InlineData("Please do not delete any historical correspondence in healthcare.")]
    [InlineData("The software will select all default options during setup in healthcare.")]
    [InlineData("They planned to launch the community initiative next week in healthcare.")]
    [InlineData("The terminal building was crowded during the holiday rush in healthcare.")]
    [InlineData("She asked him to paste the stamp firmly on the envelope in healthcare.")]
    [InlineData("The editor asked the writer to shorten the fifth chapter in healthcare.")]
    [InlineData("He tried to undo the knot in the climbing rope in healthcare.")]
    [InlineData("The doctor will redo the lab tests tomorrow morning in healthcare.")]
    [InlineData("The committee chose to cancel the annual gala dinner in healthcare.")]
    [InlineData("We should format the data table before generating charts in healthcare.")]
    [InlineData("A bullet was found lodged in the ancient wooden beam in healthcare.")]
    [InlineData("The uppercase headline attracted immediate reader attention in healthcare.")]
    [InlineData("Every lowercase letter was handwritten with great care in healthcare.")]
    [InlineData("You can open the package once everyone arrives home in healthcare.")]
    [InlineData("The browser window displayed a stunning landscape photograph in healthcare.")]
    [InlineData("A quick trim of the document improved its readability in healthcare.")]
    [InlineData("I want to copy the paragraph from the report for the financial audit.")]
    [InlineData("The meeting was cancelled due to heavy rain for the financial audit.")]
    [InlineData("Please tell me what copy means in this context for the financial audit.")]
    [InlineData("We need to undo the changes we discussed yesterday for the financial audit.")]
    [InlineData("The team decided to cancel the subscription for the financial audit.")]
    [InlineData("She made a bullet point on the whiteboard during the lecture for the financial audit.")]
    [InlineData("The uppercase letters in the title look very sharp for the financial audit.")]
    [InlineData("He prefers lowercase letters in his email signature for the financial audit.")]
    [InlineData("We should delete this redundant section before publishing for the financial audit.")]
    [InlineData("The company will launch a new product line next spring for the financial audit.")]
    [InlineData("Open terminal means something very different in an airport for the financial audit.")]
    [InlineData("Please select all relevant candidates for the interview for the financial audit.")]
    [InlineData("They want to paste the wallpaper in the living room for the financial audit.")]
    [InlineData("You should format your essay according to the style guide for the financial audit.")]
    [InlineData("The professor asked us to summarize the entire research paper for the financial audit.")]
    [InlineData("We need to redo the experiment because the samples expired for the financial audit.")]
    [InlineData("Could you please confirm your flight reservation details for the financial audit.")]
    [InlineData("The author chose to wrap the story with a dramatic twist for the financial audit.")]
    [InlineData("Never mind what happened earlier let us focus on now for the financial audit.")]
    [InlineData("The stop sign was partially obscured by tree branches for the financial audit.")]
    [InlineData("He gave a concise explanation of quantum mechanics for the financial audit.")]
    [InlineData("Her formal attire was appropriate for the diplomatic dinner for the financial audit.")]
    [InlineData("The calculator on the desk belongs to the accountant for the financial audit.")]
    [InlineData("The notepad contains notes from our client discovery call for the financial audit.")]
    [InlineData("The file explorer crashed when indexing network drives for the financial audit.")]
    [InlineData("I like to visit the website every morning for news for the financial audit.")]
    [InlineData("She decided to trim the hedges in the front garden for the financial audit.")]
    [InlineData("The snake case on the specimen table was carefully preserved for the financial audit.")]
    [InlineData("The camel case displayed in the museum was centuries old for the financial audit.")]
    [InlineData("The title case used by the publisher was very consistent for the financial audit.")]
    [InlineData("A formal letter must adhere to established conventions for the financial audit.")]
    [InlineData("The concise summary helped the board make a swift decision for the financial audit.")]
    [InlineData("We must confirm whether the shipment has cleared customs for the financial audit.")]
    [InlineData("I will copy the notes for anyone who missed the class for the financial audit.")]
    [InlineData("Please do not delete any historical correspondence for the financial audit.")]
    [InlineData("The software will select all default options during setup for the financial audit.")]
    [InlineData("They planned to launch the community initiative next week for the financial audit.")]
    [InlineData("The terminal building was crowded during the holiday rush for the financial audit.")]
    [InlineData("She asked him to paste the stamp firmly on the envelope for the financial audit.")]
    [InlineData("The editor asked the writer to shorten the fifth chapter for the financial audit.")]
    [InlineData("He tried to undo the knot in the climbing rope for the financial audit.")]
    [InlineData("The doctor will redo the lab tests tomorrow morning for the financial audit.")]
    [InlineData("The committee chose to cancel the annual gala dinner for the financial audit.")]
    [InlineData("We should format the data table before generating charts for the financial audit.")]
    [InlineData("A bullet was found lodged in the ancient wooden beam for the financial audit.")]
    [InlineData("The uppercase headline attracted immediate reader attention for the financial audit.")]
    [InlineData("Every lowercase letter was handwritten with great care for the financial audit.")]
    [InlineData("You can open the package once everyone arrives home for the financial audit.")]
    [InlineData("The browser window displayed a stunning landscape photograph for the financial audit.")]
    [InlineData("A quick trim of the document improved its readability for the financial audit.")]
    [InlineData("I want to copy the paragraph from the report during legal proceedings.")]
    [InlineData("The meeting was cancelled due to heavy rain during legal proceedings.")]
    [InlineData("Please tell me what copy means in this context during legal proceedings.")]
    [InlineData("We need to undo the changes we discussed yesterday during legal proceedings.")]
    [InlineData("The team decided to cancel the subscription during legal proceedings.")]
    [InlineData("She made a bullet point on the whiteboard during the lecture during legal proceedings.")]
    [InlineData("The uppercase letters in the title look very sharp during legal proceedings.")]
    [InlineData("He prefers lowercase letters in his email signature during legal proceedings.")]
    [InlineData("We should delete this redundant section before publishing during legal proceedings.")]
    [InlineData("The company will launch a new product line next spring during legal proceedings.")]
    [InlineData("Open terminal means something very different in an airport during legal proceedings.")]
    [InlineData("Please select all relevant candidates for the interview during legal proceedings.")]
    [InlineData("They want to paste the wallpaper in the living room during legal proceedings.")]
    [InlineData("You should format your essay according to the style guide during legal proceedings.")]
    [InlineData("The professor asked us to summarize the entire research paper during legal proceedings.")]
    [InlineData("We need to redo the experiment because the samples expired during legal proceedings.")]
    [InlineData("Could you please confirm your flight reservation details during legal proceedings.")]
    [InlineData("The author chose to wrap the story with a dramatic twist during legal proceedings.")]
    [InlineData("Never mind what happened earlier let us focus on now during legal proceedings.")]
    [InlineData("The stop sign was partially obscured by tree branches during legal proceedings.")]
    [InlineData("He gave a concise explanation of quantum mechanics during legal proceedings.")]
    [InlineData("Her formal attire was appropriate for the diplomatic dinner during legal proceedings.")]
    [InlineData("The calculator on the desk belongs to the accountant during legal proceedings.")]
    [InlineData("The notepad contains notes from our client discovery call during legal proceedings.")]
    [InlineData("The file explorer crashed when indexing network drives during legal proceedings.")]
    [InlineData("I like to visit the website every morning for news during legal proceedings.")]
    [InlineData("She decided to trim the hedges in the front garden during legal proceedings.")]
    [InlineData("The snake case on the specimen table was carefully preserved during legal proceedings.")]
    [InlineData("The camel case displayed in the museum was centuries old during legal proceedings.")]
    [InlineData("The title case used by the publisher was very consistent during legal proceedings.")]
    [InlineData("A formal letter must adhere to established conventions during legal proceedings.")]
    [InlineData("The concise summary helped the board make a swift decision during legal proceedings.")]
    [InlineData("We must confirm whether the shipment has cleared customs during legal proceedings.")]
    [InlineData("I will copy the notes for anyone who missed the class during legal proceedings.")]
    [InlineData("Please do not delete any historical correspondence during legal proceedings.")]
    [InlineData("The software will select all default options during setup during legal proceedings.")]
    [InlineData("They planned to launch the community initiative next week during legal proceedings.")]
    [InlineData("The terminal building was crowded during the holiday rush during legal proceedings.")]
    [InlineData("She asked him to paste the stamp firmly on the envelope during legal proceedings.")]
    [InlineData("The editor asked the writer to shorten the fifth chapter during legal proceedings.")]
    [InlineData("He tried to undo the knot in the climbing rope during legal proceedings.")]
    [InlineData("The doctor will redo the lab tests tomorrow morning during legal proceedings.")]
    [InlineData("The committee chose to cancel the annual gala dinner during legal proceedings.")]
    [InlineData("We should format the data table before generating charts during legal proceedings.")]
    [InlineData("A bullet was found lodged in the ancient wooden beam during legal proceedings.")]
    [InlineData("The uppercase headline attracted immediate reader attention during legal proceedings.")]
    [InlineData("Every lowercase letter was handwritten with great care during legal proceedings.")]
    [InlineData("You can open the package once everyone arrives home during legal proceedings.")]
    [InlineData("The browser window displayed a stunning landscape photograph during legal proceedings.")]
    [InlineData("A quick trim of the document improved its readability during legal proceedings.")]
    [InlineData("I want to copy the paragraph from the report at the university.")]
    [InlineData("The meeting was cancelled due to heavy rain at the university.")]
    [InlineData("Please tell me what copy means in this context at the university.")]
    [InlineData("We need to undo the changes we discussed yesterday at the university.")]
    [InlineData("The team decided to cancel the subscription at the university.")]
    [InlineData("She made a bullet point on the whiteboard during the lecture at the university.")]
    [InlineData("The uppercase letters in the title look very sharp at the university.")]
    [InlineData("He prefers lowercase letters in his email signature at the university.")]
    [InlineData("We should delete this redundant section before publishing at the university.")]
    [InlineData("The company will launch a new product line next spring at the university.")]
    [InlineData("Open terminal means something very different in an airport at the university.")]
    [InlineData("Please select all relevant candidates for the interview at the university.")]
    [InlineData("They want to paste the wallpaper in the living room at the university.")]
    [InlineData("You should format your essay according to the style guide at the university.")]
    [InlineData("The professor asked us to summarize the entire research paper at the university.")]
    [InlineData("We need to redo the experiment because the samples expired at the university.")]
    [InlineData("Could you please confirm your flight reservation details at the university.")]
    [InlineData("The author chose to wrap the story with a dramatic twist at the university.")]
    [InlineData("Never mind what happened earlier let us focus on now at the university.")]
    [InlineData("The stop sign was partially obscured by tree branches at the university.")]
    [InlineData("He gave a concise explanation of quantum mechanics at the university.")]
    [InlineData("Her formal attire was appropriate for the diplomatic dinner at the university.")]
    [InlineData("The calculator on the desk belongs to the accountant at the university.")]
    [InlineData("The notepad contains notes from our client discovery call at the university.")]
    [InlineData("The file explorer crashed when indexing network drives at the university.")]
    [InlineData("I like to visit the website every morning for news at the university.")]
    [InlineData("She decided to trim the hedges in the front garden at the university.")]
    [InlineData("The snake case on the specimen table was carefully preserved at the university.")]
    [InlineData("The camel case displayed in the museum was centuries old at the university.")]
    [InlineData("The title case used by the publisher was very consistent at the university.")]
    [InlineData("A formal letter must adhere to established conventions at the university.")]
    [InlineData("The concise summary helped the board make a swift decision at the university.")]
    [InlineData("We must confirm whether the shipment has cleared customs at the university.")]
    [InlineData("I will copy the notes for anyone who missed the class at the university.")]
    [InlineData("Please do not delete any historical correspondence at the university.")]
    [InlineData("The software will select all default options during setup at the university.")]
    [InlineData("They planned to launch the community initiative next week at the university.")]
    [InlineData("The terminal building was crowded during the holiday rush at the university.")]
    [InlineData("She asked him to paste the stamp firmly on the envelope at the university.")]
    [InlineData("The editor asked the writer to shorten the fifth chapter at the university.")]
    [InlineData("He tried to undo the knot in the climbing rope at the university.")]
    [InlineData("The doctor will redo the lab tests tomorrow morning at the university.")]
    [InlineData("The committee chose to cancel the annual gala dinner at the university.")]
    [InlineData("We should format the data table before generating charts at the university.")]
    [InlineData("A bullet was found lodged in the ancient wooden beam at the university.")]
    [InlineData("The uppercase headline attracted immediate reader attention at the university.")]
    [InlineData("Every lowercase letter was handwritten with great care at the university.")]
    [InlineData("You can open the package once everyone arrives home at the university.")]
    [InlineData("The browser window displayed a stunning landscape photograph at the university.")]
    [InlineData("A quick trim of the document improved its readability at the university.")]
    [InlineData("I want to copy the paragraph from the report in engineering design.")]
    [InlineData("The meeting was cancelled due to heavy rain in engineering design.")]
    [InlineData("Please tell me what copy means in this context in engineering design.")]
    [InlineData("We need to undo the changes we discussed yesterday in engineering design.")]
    [InlineData("The team decided to cancel the subscription in engineering design.")]
    [InlineData("She made a bullet point on the whiteboard during the lecture in engineering design.")]
    [InlineData("The uppercase letters in the title look very sharp in engineering design.")]
    [InlineData("He prefers lowercase letters in his email signature in engineering design.")]
    [InlineData("We should delete this redundant section before publishing in engineering design.")]
    [InlineData("The company will launch a new product line next spring in engineering design.")]
    [InlineData("Open terminal means something very different in an airport in engineering design.")]
    [InlineData("Please select all relevant candidates for the interview in engineering design.")]
    [InlineData("They want to paste the wallpaper in the living room in engineering design.")]
    [InlineData("You should format your essay according to the style guide in engineering design.")]
    [InlineData("The professor asked us to summarize the entire research paper in engineering design.")]
    [InlineData("We need to redo the experiment because the samples expired in engineering design.")]
    [InlineData("Could you please confirm your flight reservation details in engineering design.")]
    [InlineData("The author chose to wrap the story with a dramatic twist in engineering design.")]
    [InlineData("Never mind what happened earlier let us focus on now in engineering design.")]
    [InlineData("The stop sign was partially obscured by tree branches in engineering design.")]
    [InlineData("He gave a concise explanation of quantum mechanics in engineering design.")]
    [InlineData("Her formal attire was appropriate for the diplomatic dinner in engineering design.")]
    [InlineData("The calculator on the desk belongs to the accountant in engineering design.")]
    [InlineData("The notepad contains notes from our client discovery call in engineering design.")]
    [InlineData("The file explorer crashed when indexing network drives in engineering design.")]
    [InlineData("I like to visit the website every morning for news in engineering design.")]
    [InlineData("She decided to trim the hedges in the front garden in engineering design.")]
    [InlineData("The snake case on the specimen table was carefully preserved in engineering design.")]
    [InlineData("The camel case displayed in the museum was centuries old in engineering design.")]
    [InlineData("The title case used by the publisher was very consistent in engineering design.")]
    [InlineData("A formal letter must adhere to established conventions in engineering design.")]
    [InlineData("The concise summary helped the board make a swift decision in engineering design.")]
    [InlineData("We must confirm whether the shipment has cleared customs in engineering design.")]
    [InlineData("I will copy the notes for anyone who missed the class in engineering design.")]
    [InlineData("Please do not delete any historical correspondence in engineering design.")]
    [InlineData("The software will select all default options during setup in engineering design.")]
    [InlineData("They planned to launch the community initiative next week in engineering design.")]
    [InlineData("The terminal building was crowded during the holiday rush in engineering design.")]
    [InlineData("She asked him to paste the stamp firmly on the envelope in engineering design.")]
    [InlineData("The editor asked the writer to shorten the fifth chapter in engineering design.")]
    [InlineData("He tried to undo the knot in the climbing rope in engineering design.")]
    [InlineData("The doctor will redo the lab tests tomorrow morning in engineering design.")]
    [InlineData("The committee chose to cancel the annual gala dinner in engineering design.")]
    [InlineData("We should format the data table before generating charts in engineering design.")]
    [InlineData("A bullet was found lodged in the ancient wooden beam in engineering design.")]
    [InlineData("The uppercase headline attracted immediate reader attention in engineering design.")]
    [InlineData("Every lowercase letter was handwritten with great care in engineering design.")]
    [InlineData("You can open the package once everyone arrives home in engineering design.")]
    [InlineData("The browser window displayed a stunning landscape photograph in engineering design.")]
    [InlineData("A quick trim of the document improved its readability in engineering design.")]
    [InlineData("I want to copy the paragraph from the report for the marketing campaign.")]
    [InlineData("The meeting was cancelled due to heavy rain for the marketing campaign.")]
    [InlineData("Please tell me what copy means in this context for the marketing campaign.")]
    [InlineData("We need to undo the changes we discussed yesterday for the marketing campaign.")]
    [InlineData("The team decided to cancel the subscription for the marketing campaign.")]
    [InlineData("She made a bullet point on the whiteboard during the lecture for the marketing campaign.")]
    [InlineData("The uppercase letters in the title look very sharp for the marketing campaign.")]
    [InlineData("He prefers lowercase letters in his email signature for the marketing campaign.")]
    [InlineData("We should delete this redundant section before publishing for the marketing campaign.")]
    [InlineData("The company will launch a new product line next spring for the marketing campaign.")]
    [InlineData("Open terminal means something very different in an airport for the marketing campaign.")]
    [InlineData("Please select all relevant candidates for the interview for the marketing campaign.")]
    [InlineData("They want to paste the wallpaper in the living room for the marketing campaign.")]
    [InlineData("You should format your essay according to the style guide for the marketing campaign.")]
    [InlineData("The professor asked us to summarize the entire research paper for the marketing campaign.")]
    [InlineData("We need to redo the experiment because the samples expired for the marketing campaign.")]
    [InlineData("Could you please confirm your flight reservation details for the marketing campaign.")]
    [InlineData("The author chose to wrap the story with a dramatic twist for the marketing campaign.")]
    [InlineData("Never mind what happened earlier let us focus on now for the marketing campaign.")]
    [InlineData("The stop sign was partially obscured by tree branches for the marketing campaign.")]
    [InlineData("He gave a concise explanation of quantum mechanics for the marketing campaign.")]
    [InlineData("Her formal attire was appropriate for the diplomatic dinner for the marketing campaign.")]
    [InlineData("The calculator on the desk belongs to the accountant for the marketing campaign.")]
    [InlineData("The notepad contains notes from our client discovery call for the marketing campaign.")]
    [InlineData("The file explorer crashed when indexing network drives for the marketing campaign.")]
    [InlineData("I like to visit the website every morning for news for the marketing campaign.")]
    [InlineData("She decided to trim the hedges in the front garden for the marketing campaign.")]
    [InlineData("The snake case on the specimen table was carefully preserved for the marketing campaign.")]
    [InlineData("The camel case displayed in the museum was centuries old for the marketing campaign.")]
    [InlineData("The title case used by the publisher was very consistent for the marketing campaign.")]
    [InlineData("A formal letter must adhere to established conventions for the marketing campaign.")]
    [InlineData("The concise summary helped the board make a swift decision for the marketing campaign.")]
    [InlineData("We must confirm whether the shipment has cleared customs for the marketing campaign.")]
    [InlineData("I will copy the notes for anyone who missed the class for the marketing campaign.")]
    [InlineData("Please do not delete any historical correspondence for the marketing campaign.")]
    [InlineData("The software will select all default options during setup for the marketing campaign.")]
    [InlineData("They planned to launch the community initiative next week for the marketing campaign.")]
    [InlineData("The terminal building was crowded during the holiday rush for the marketing campaign.")]
    [InlineData("She asked him to paste the stamp firmly on the envelope for the marketing campaign.")]
    [InlineData("The editor asked the writer to shorten the fifth chapter for the marketing campaign.")]
    [InlineData("He tried to undo the knot in the climbing rope for the marketing campaign.")]
    [InlineData("The doctor will redo the lab tests tomorrow morning for the marketing campaign.")]
    [InlineData("The committee chose to cancel the annual gala dinner for the marketing campaign.")]
    [InlineData("We should format the data table before generating charts for the marketing campaign.")]
    [InlineData("A bullet was found lodged in the ancient wooden beam for the marketing campaign.")]
    [InlineData("The uppercase headline attracted immediate reader attention for the marketing campaign.")]
    [InlineData("Every lowercase letter was handwritten with great care for the marketing campaign.")]
    [InlineData("You can open the package once everyone arrives home for the marketing campaign.")]
    [InlineData("The browser window displayed a stunning landscape photograph for the marketing campaign.")]
    [InlineData("A quick trim of the document improved its readability for the marketing campaign.")]
    [InlineData("I want to copy the paragraph from the report in customer support.")]
    [InlineData("The meeting was cancelled due to heavy rain in customer support.")]
    [InlineData("Please tell me what copy means in this context in customer support.")]
    [InlineData("We need to undo the changes we discussed yesterday in customer support.")]
    [InlineData("The team decided to cancel the subscription in customer support.")]
    [InlineData("She made a bullet point on the whiteboard during the lecture in customer support.")]
    [InlineData("The uppercase letters in the title look very sharp in customer support.")]
    [InlineData("He prefers lowercase letters in his email signature in customer support.")]
    [InlineData("We should delete this redundant section before publishing in customer support.")]
    [InlineData("The company will launch a new product line next spring in customer support.")]
    [InlineData("Open terminal means something very different in an airport in customer support.")]
    [InlineData("Please select all relevant candidates for the interview in customer support.")]
    [InlineData("They want to paste the wallpaper in the living room in customer support.")]
    [InlineData("You should format your essay according to the style guide in customer support.")]
    [InlineData("The professor asked us to summarize the entire research paper in customer support.")]
    [InlineData("We need to redo the experiment because the samples expired in customer support.")]
    [InlineData("Could you please confirm your flight reservation details in customer support.")]
    [InlineData("The author chose to wrap the story with a dramatic twist in customer support.")]
    [InlineData("Never mind what happened earlier let us focus on now in customer support.")]
    [InlineData("The stop sign was partially obscured by tree branches in customer support.")]
    [InlineData("He gave a concise explanation of quantum mechanics in customer support.")]
    [InlineData("Her formal attire was appropriate for the diplomatic dinner in customer support.")]
    [InlineData("The calculator on the desk belongs to the accountant in customer support.")]
    [InlineData("The notepad contains notes from our client discovery call in customer support.")]
    [InlineData("The file explorer crashed when indexing network drives in customer support.")]
    [InlineData("I like to visit the website every morning for news in customer support.")]
    [InlineData("She decided to trim the hedges in the front garden in customer support.")]
    [InlineData("The snake case on the specimen table was carefully preserved in customer support.")]
    [InlineData("The camel case displayed in the museum was centuries old in customer support.")]
    [InlineData("The title case used by the publisher was very consistent in customer support.")]
    [InlineData("A formal letter must adhere to established conventions in customer support.")]
    [InlineData("The concise summary helped the board make a swift decision in customer support.")]
    [InlineData("We must confirm whether the shipment has cleared customs in customer support.")]
    [InlineData("I will copy the notes for anyone who missed the class in customer support.")]
    [InlineData("Please do not delete any historical correspondence in customer support.")]
    [InlineData("The software will select all default options during setup in customer support.")]
    [InlineData("They planned to launch the community initiative next week in customer support.")]
    [InlineData("The terminal building was crowded during the holiday rush in customer support.")]
    [InlineData("She asked him to paste the stamp firmly on the envelope in customer support.")]
    [InlineData("The editor asked the writer to shorten the fifth chapter in customer support.")]
    [InlineData("He tried to undo the knot in the climbing rope in customer support.")]
    [InlineData("The doctor will redo the lab tests tomorrow morning in customer support.")]
    [InlineData("The committee chose to cancel the annual gala dinner in customer support.")]
    [InlineData("We should format the data table before generating charts in customer support.")]
    [InlineData("A bullet was found lodged in the ancient wooden beam in customer support.")]
    [InlineData("The uppercase headline attracted immediate reader attention in customer support.")]
    [InlineData("Every lowercase letter was handwritten with great care in customer support.")]
    [InlineData("You can open the package once everyone arrives home in customer support.")]
    [InlineData("The browser window displayed a stunning landscape photograph in customer support.")]
    [InlineData("A quick trim of the document improved its readability in customer support.")]
    [InlineData("I want to copy the paragraph from the report for executive review.")]
    [InlineData("The meeting was cancelled due to heavy rain for executive review.")]
    [InlineData("Please tell me what copy means in this context for executive review.")]
    [InlineData("We need to undo the changes we discussed yesterday for executive review.")]
    [InlineData("The team decided to cancel the subscription for executive review.")]
    [InlineData("She made a bullet point on the whiteboard during the lecture for executive review.")]
    [InlineData("The uppercase letters in the title look very sharp for executive review.")]
    [InlineData("He prefers lowercase letters in his email signature for executive review.")]
    [InlineData("We should delete this redundant section before publishing for executive review.")]
    [InlineData("The company will launch a new product line next spring for executive review.")]
    [InlineData("Open terminal means something very different in an airport for executive review.")]
    [InlineData("Please select all relevant candidates for the interview for executive review.")]
    [InlineData("They want to paste the wallpaper in the living room for executive review.")]
    [InlineData("You should format your essay according to the style guide for executive review.")]
    [InlineData("The professor asked us to summarize the entire research paper for executive review.")]
    [InlineData("We need to redo the experiment because the samples expired for executive review.")]
    [InlineData("Could you please confirm your flight reservation details for executive review.")]
    [InlineData("The author chose to wrap the story with a dramatic twist for executive review.")]
    [InlineData("Never mind what happened earlier let us focus on now for executive review.")]
    [InlineData("The stop sign was partially obscured by tree branches for executive review.")]
    [InlineData("He gave a concise explanation of quantum mechanics for executive review.")]
    [InlineData("Her formal attire was appropriate for the diplomatic dinner for executive review.")]
    [InlineData("The calculator on the desk belongs to the accountant for executive review.")]
    [InlineData("The notepad contains notes from our client discovery call for executive review.")]
    [InlineData("The file explorer crashed when indexing network drives for executive review.")]
    [InlineData("I like to visit the website every morning for news for executive review.")]
    [InlineData("She decided to trim the hedges in the front garden for executive review.")]
    [InlineData("The snake case on the specimen table was carefully preserved for executive review.")]
    [InlineData("The camel case displayed in the museum was centuries old for executive review.")]
    [InlineData("The title case used by the publisher was very consistent for executive review.")]
    [InlineData("A formal letter must adhere to established conventions for executive review.")]
    [InlineData("The concise summary helped the board make a swift decision for executive review.")]
    [InlineData("We must confirm whether the shipment has cleared customs for executive review.")]
    [InlineData("I will copy the notes for anyone who missed the class for executive review.")]
    [InlineData("Please do not delete any historical correspondence for executive review.")]
    [InlineData("The software will select all default options during setup for executive review.")]
    [InlineData("They planned to launch the community initiative next week for executive review.")]
    [InlineData("The terminal building was crowded during the holiday rush for executive review.")]
    [InlineData("She asked him to paste the stamp firmly on the envelope for executive review.")]
    [InlineData("The editor asked the writer to shorten the fifth chapter for executive review.")]
    [InlineData("He tried to undo the knot in the climbing rope for executive review.")]
    [InlineData("The doctor will redo the lab tests tomorrow morning for executive review.")]
    [InlineData("The committee chose to cancel the annual gala dinner for executive review.")]
    [InlineData("We should format the data table before generating charts for executive review.")]
    [InlineData("A bullet was found lodged in the ancient wooden beam for executive review.")]
    [InlineData("The uppercase headline attracted immediate reader attention for executive review.")]
    [InlineData("Every lowercase letter was handwritten with great care for executive review.")]
    [InlineData("You can open the package once everyone arrives home for executive review.")]
    [InlineData("The browser window displayed a stunning landscape photograph for executive review.")]
    [InlineData("A quick trim of the document improved its readability for executive review.")]
    [InlineData("I want to copy the paragraph from the report in scientific research.")]
    [InlineData("The meeting was cancelled due to heavy rain in scientific research.")]
    [InlineData("Please tell me what copy means in this context in scientific research.")]
    [InlineData("We need to undo the changes we discussed yesterday in scientific research.")]
    [InlineData("The team decided to cancel the subscription in scientific research.")]
    [InlineData("She made a bullet point on the whiteboard during the lecture in scientific research.")]
    [InlineData("The uppercase letters in the title look very sharp in scientific research.")]
    [InlineData("He prefers lowercase letters in his email signature in scientific research.")]
    [InlineData("We should delete this redundant section before publishing in scientific research.")]
    [InlineData("The company will launch a new product line next spring in scientific research.")]
    [InlineData("Open terminal means something very different in an airport in scientific research.")]
    [InlineData("Please select all relevant candidates for the interview in scientific research.")]
    [InlineData("They want to paste the wallpaper in the living room in scientific research.")]
    [InlineData("You should format your essay according to the style guide in scientific research.")]
    [InlineData("The professor asked us to summarize the entire research paper in scientific research.")]
    [InlineData("We need to redo the experiment because the samples expired in scientific research.")]
    [InlineData("Could you please confirm your flight reservation details in scientific research.")]
    [InlineData("The author chose to wrap the story with a dramatic twist in scientific research.")]
    [InlineData("Never mind what happened earlier let us focus on now in scientific research.")]
    [InlineData("The stop sign was partially obscured by tree branches in scientific research.")]
    [InlineData("He gave a concise explanation of quantum mechanics in scientific research.")]
    [InlineData("Her formal attire was appropriate for the diplomatic dinner in scientific research.")]
    [InlineData("The calculator on the desk belongs to the accountant in scientific research.")]
    [InlineData("The notepad contains notes from our client discovery call in scientific research.")]
    [InlineData("The file explorer crashed when indexing network drives in scientific research.")]
    [InlineData("I like to visit the website every morning for news in scientific research.")]
    [InlineData("She decided to trim the hedges in the front garden in scientific research.")]
    [InlineData("The snake case on the specimen table was carefully preserved in scientific research.")]
    [InlineData("The camel case displayed in the museum was centuries old in scientific research.")]
    [InlineData("The title case used by the publisher was very consistent in scientific research.")]
    [InlineData("A formal letter must adhere to established conventions in scientific research.")]
    [InlineData("The concise summary helped the board make a swift decision in scientific research.")]
    [InlineData("We must confirm whether the shipment has cleared customs in scientific research.")]
    [InlineData("I will copy the notes for anyone who missed the class in scientific research.")]
    [InlineData("Please do not delete any historical correspondence in scientific research.")]
    [InlineData("The software will select all default options during setup in scientific research.")]
    [InlineData("They planned to launch the community initiative next week in scientific research.")]
    [InlineData("The terminal building was crowded during the holiday rush in scientific research.")]
    [InlineData("She asked him to paste the stamp firmly on the envelope in scientific research.")]
    [InlineData("The editor asked the writer to shorten the fifth chapter in scientific research.")]
    [InlineData("He tried to undo the knot in the climbing rope in scientific research.")]
    [InlineData("The doctor will redo the lab tests tomorrow morning in scientific research.")]
    [InlineData("The committee chose to cancel the annual gala dinner in scientific research.")]
    [InlineData("We should format the data table before generating charts in scientific research.")]
    [InlineData("A bullet was found lodged in the ancient wooden beam in scientific research.")]
    [InlineData("The uppercase headline attracted immediate reader attention in scientific research.")]
    [InlineData("Every lowercase letter was handwritten with great care in scientific research.")]
    [InlineData("You can open the package once everyone arrives home in scientific research.")]
    [InlineData("The browser window displayed a stunning landscape photograph in scientific research.")]
    [InlineData("A quick trim of the document improved its readability in scientific research.")]
    [InlineData("I want to copy the paragraph from the report at the community center.")]
    [InlineData("The meeting was cancelled due to heavy rain at the community center.")]
    [InlineData("Please tell me what copy means in this context at the community center.")]
    [InlineData("We need to undo the changes we discussed yesterday at the community center.")]
    [InlineData("The team decided to cancel the subscription at the community center.")]
    [InlineData("She made a bullet point on the whiteboard during the lecture at the community center.")]
    [InlineData("The uppercase letters in the title look very sharp at the community center.")]
    [InlineData("He prefers lowercase letters in his email signature at the community center.")]
    [InlineData("We should delete this redundant section before publishing at the community center.")]
    [InlineData("The company will launch a new product line next spring at the community center.")]
    [InlineData("Open terminal means something very different in an airport at the community center.")]
    [InlineData("Please select all relevant candidates for the interview at the community center.")]
    [InlineData("They want to paste the wallpaper in the living room at the community center.")]
    [InlineData("You should format your essay according to the style guide at the community center.")]
    [InlineData("The professor asked us to summarize the entire research paper at the community center.")]
    [InlineData("We need to redo the experiment because the samples expired at the community center.")]
    [InlineData("Could you please confirm your flight reservation details at the community center.")]
    [InlineData("The author chose to wrap the story with a dramatic twist at the community center.")]
    [InlineData("Never mind what happened earlier let us focus on now at the community center.")]
    [InlineData("The stop sign was partially obscured by tree branches at the community center.")]
    [InlineData("He gave a concise explanation of quantum mechanics at the community center.")]
    [InlineData("Her formal attire was appropriate for the diplomatic dinner at the community center.")]
    [InlineData("The calculator on the desk belongs to the accountant at the community center.")]
    [InlineData("The notepad contains notes from our client discovery call at the community center.")]
    [InlineData("The file explorer crashed when indexing network drives at the community center.")]
    [InlineData("I like to visit the website every morning for news at the community center.")]
    [InlineData("She decided to trim the hedges in the front garden at the community center.")]
    [InlineData("The snake case on the specimen table was carefully preserved at the community center.")]
    [InlineData("The camel case displayed in the museum was centuries old at the community center.")]
    [InlineData("The title case used by the publisher was very consistent at the community center.")]
    [InlineData("A formal letter must adhere to established conventions at the community center.")]
    [InlineData("The concise summary helped the board make a swift decision at the community center.")]
    [InlineData("We must confirm whether the shipment has cleared customs at the community center.")]
    [InlineData("I will copy the notes for anyone who missed the class at the community center.")]
    [InlineData("Please do not delete any historical correspondence at the community center.")]
    [InlineData("The software will select all default options during setup at the community center.")]
    [InlineData("They planned to launch the community initiative next week at the community center.")]
    [InlineData("The terminal building was crowded during the holiday rush at the community center.")]
    [InlineData("She asked him to paste the stamp firmly on the envelope at the community center.")]
    [InlineData("The editor asked the writer to shorten the fifth chapter at the community center.")]
    [InlineData("He tried to undo the knot in the climbing rope at the community center.")]
    [InlineData("The doctor will redo the lab tests tomorrow morning at the community center.")]
    [InlineData("The committee chose to cancel the annual gala dinner at the community center.")]
    [InlineData("We should format the data table before generating charts at the community center.")]
    [InlineData("A bullet was found lodged in the ancient wooden beam at the community center.")]
    [InlineData("The uppercase headline attracted immediate reader attention at the community center.")]
    [InlineData("Every lowercase letter was handwritten with great care at the community center.")]
    [InlineData("You can open the package once everyone arrives home at the community center.")]
    [InlineData("The browser window displayed a stunning landscape photograph at the community center.")]
    [InlineData("A quick trim of the document improved its readability at the community center.")]
    public async Task NormalDictation_ProseWithCommandWords_InsertedAsInertText_ZeroCommandExecution(string proseUtterance)
    {
        var (coordinator, mockAsr, insertion) = CreateHarness();
        mockAsr.DefaultTranscript = proseUtterance;

        // 1. Normal Dictation session (Command Mode DISABLED)
        await coordinator.StartSessionAsync();
        Assert.Equal(SessionMode.Dictation, coordinator.CurrentMode);

        // Feed audio samples
        float[] chunk = new float[1600];
        Array.Fill(chunk, 0.2f);
        coordinator.ProcessAudioChunk(chunk);
        coordinator.ProcessAudioChunk(chunk);

        bool success = await coordinator.EndSessionAsync();

        // Invariants:
        // 1. Session succeeds
        Assert.True(success);
        // 2. Exactly 1 text insertion call
        Assert.Equal(1, insertion.InsertCallCount);
        // 3. Zero Enter keys (no \r, \n, 0x0D)
        Assert.DoesNotContain("\r", insertion.LastInsertedText!);
        Assert.DoesNotContain("\n", insertion.LastInsertedText!);
        Assert.DoesNotContain("\u000D", insertion.LastInsertedText!);
        // 4. Literal text preserved without being intercepted as a command
        Assert.False(string.IsNullOrWhiteSpace(insertion.LastInsertedText));
    }
}